In [ ]:
codes[]

In [280]:
def augment():
    df = pd.read_csv('/home/GAstruc/Téléchargements/test.csv')
    l = []
    # Open the TIFF image using rasterio
    image_path = "/home/GAstruc/Documents/glc_shv10_DOM.Tif"
    image = imageio.imread(image_path)
    with rasterio.open(image_path) as dataset:
        # Get the image's coordinate transformation (affine transformation matrix)
        transform = dataset.transform
        for i in range (len(df)):
            x, y = ~transform * (df.loc[i,'longitude'], df.loc[i,'latitude'])
            pixel_x, pixel_y = int(x), int(y)
            l.append(image[pixel_y, pixel_x])
    
    df['land_cover'] = l
    print(len(df))
    df_road = pd.read_csv('/home/GAstruc/indicator.csv')
    df_road.columns = ['index', 'country', 'road_index']
    df_final = df.merge(df_road[['country', 'road_index']], how='left', on='country')
    print(len(df_final))
    alph = []
    df_car = pd.read_csv('/home/GAstruc/snap/firefox/common/Téléchargements/countries-that-drive-on-the-left-2023.csv')
    codes = pd.read_csv('/home/GAstruc/snap/firefox/common/Téléchargements/all.csv')
    cars = list(df_car['country'])
    for i in range (len(codes)):
        if codes.loc[i,'name'] in cars:
            alph.append(codes.loc[i,'alpha-2'])

    l = []
    for i in range (len(df_final)):
        if df_final.loc[i,'country'] in alph:
            l.append(1)
        else:
            l.append(0)

    df_final['drive_side'] = l
    print(len(df_final))

    image_path = "/home/GAstruc/Documents/Beck_KG_V1_present_0p0083.tif"
    image = imageio.imread(image_path)
    l = []
    with rasterio.open(image_path) as dataset:
        # Get the image's coordinate transformation (affine transformation matrix)
        transform = dataset.transform
        for i in range (len(df_final)):
            x, y = ~transform * (df_final.loc[i,'longitude'], df_final.loc[i,'latitude'])
            pixel_x, pixel_y = int(x), int(y)
            l.append(image[pixel_y, pixel_x])
    
    df_final['climate'] = l
    print(len(df_final))

    l = []
    image_path = "/home/GAstruc/Documents/world_soil_fao.tif"
    image = imageio.imread(image_path)
    with rasterio.open(image_path) as dataset:
        # Get the image's coordinate transformation (affine transformation matrix)
        transform = dataset.transform
        for i in range (len(df)):
            x, y = ~transform * (df.loc[i,'longitude'], df.loc[i,'latitude'])
            pixel_x, pixel_y = int(x), int(y)
            if image[pixel_y, pixel_x] == 65535:
                l.append(14)
            else:
                l.append(image[pixel_y, pixel_x])

    df_final['soil'] = l
    print(len(df_final))

    coast = gpd.read_file("/home/GAstruc/Documents/sg048gr3784.shp").to_crs('EPSG:3087')
    points_df = gpd.GeoDataFrame({
        'geometry': [
            Point(df_final.loc[i,'longitude'], df_final.loc[i,'latitude']) for i in range (len(df_final))]}, crs='EPSG:4326')
    points_df = points_df.to_crs('EPSG:3087')
    points_df['min_dist_to_coast'] = points_df.geometry.apply(min_distance, args=(coast,))

    df_final['dist_sea'] = list(points_df['min_dist_to_coast'])
    print(len(df_final))

    return(df_final)

In [279]:
train = augment()

/tmp/ipykernel_378704/2049859299.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

631982
631982
631982

/tmp/ipykernel_378704/2049859299.py:40: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

631982

/tmp/ipykernel_378704/2049859299.py:55: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

631982
631982

In [281]:
test = augment()

/tmp/ipykernel_378704/1068663698.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

46954
46954
46954

/tmp/ipykernel_378704/1068663698.py:40: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

46954

/tmp/ipykernel_378704/1068663698.py:55: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_path)

46954
46954

In [282]:
scaler = preprocessing.MinMaxScaler()
d = scaler.fit_transform(train[['road_index', 'dist_sea']])
train['road_index'] = d[:,0]
train['dist_sea'] = d[:,1]
d = scaler.transform(test[['road_index', 'dist_sea']])
test['road_index'] = d[:,0]
test['dist_sea'] = d[:,1]

In [283]:
np.unique(train['climate'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=uint8)

In [284]:
np.unique(test['climate'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=uint8)

In [286]:
sum(train['climate'] == 30)

5

In [289]:
train.to_csv('/home/GAstruc/train.csv')

In [290]:
test.to_csv('/home/GAstruc/test.csv')

In [87]:
pd.read_csv('/home/GAstruc/test.csv')

,Unnamed: 0,id,sequence,latitude,longitude,captured_at,computed_compass_angle,thumb_original_url,thumb_256_url,speed,category,city,country,land_cover,road_index,drive_side,climate,soil,dist_sea
0,0,979252696446,Wf1Y9IgOkcBQxD83v0NiKE,-43.821361,-176.481814,1652192994040,324.766884,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8k0_2jJCoJsr28Vo-q8R6xJlMMC3NMmgoU3pXFxqsI6-ZwPmp8L4OZvrHt47zq6d8dHEfPs11fE-FNfSlOBiyzKgVm3tgJizgaj0r6KvzCG9zhqPBJxmk01Krg5h_0qsst2QIUlEpj-s50lf9VOQw?ccb=10-5&oh=00_AfDb_f4wuACVLOeAW_T5FRv9qvRPqi13DcCjORvZrxA7CA&oe=64CAE61E&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8k0_2jJCoJsr28Vo-q8R6xJlMMC3NMmgoU3pXFxqsI6-ZwPmp8L4OZvrHt47zq6d8dHEfPs11fE-FNfSlOBiyzKgVm3tgJizgaj0r6KvzCG9zhqPBJxmk01Krg5h_0qsst2QIUlEpj-s50lf9VOQw?stp=s256x144&ccb=10-5&oh=00_AfBOlEz5pqfJgw358r_67DABX1srBXLV6Eh_Eez-5m67_g&oe=64CAE61E&_nc_sid=201bca,14.864665,0,Waitangi,NZ,3,0.608575,1,15,14,0.000823
1,1,979252696096,1WEuplcV5NHSFbKfhm0dUP,-43.821250,-176.481661,1633956847398,156.000000,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An-0TgyI8cPl4O6Rzyd-laHr5Npx5y1sZAnpSrphQBbcbJjV1u9limTfA1Yl3oPMpugeCKEEFM70zo2xLEhrPWB2J5CAHsMsaoLUX4U7-eFVx6Rw43KLkeRIeNqHJkBsOg21gd6Fmc_uoNEu31Js9w?ccb=10-5&oh=00_AfDxgDk2KAdc--bU8WPUyFiFkOH4kTRTQW4rAb5o3f2Ypg&oe=64CB024B&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An-0TgyI8cPl4O6Rzyd-laHr5Npx5y1sZAnpSrphQBbcbJjV1u9limTfA1Yl3oPMpugeCKEEFM70zo2xLEhrPWB2J5CAHsMsaoLUX4U7-eFVx6Rw43KLkeRIeNqHJkBsOg21gd6Fmc_uoNEu31Js9w?stp=s256x144&ccb=10-5&oh=00_AfC3ekLLz-tf-yDnvSpw09CxrTad5xLcaUo4fnp0vl-mWg&oe=64CB024B&_nc_sid=201bca,13.329369,0,Waitangi,NZ,3,0.608575,1,15,14,0.000823
2,2,979252696720,E8WcmBvHsaVIz5oXUpODlZ,-43.821125,-176.482003,1672926398361,184.383326,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9UbDq-U8jGIFdmFTqtk4gKLHUvPS60tONfTIr8cXnZKpLhCcAkgrkiLEXdNI-Vi42K7qN_QEtNMahbZRAJHpdrUXrm4nfyMqceePLgvRAF91ulTRd_Aomt11GE4HY4tLCwbV2BsvO4-TYL1bTglqU?ccb=10-5&oh=00_AfBQmVZ35d5O4RD6T3vdWcgvWmsJgYO1vG4lQy2CQT9vEg&oe=64CB1005&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9UbDq-U8jGIFdmFTqtk4gKLHUvPS60tONfTIr8cXnZKpLhCcAkgrkiLEXdNI-Vi42K7qN_QEtNMahbZRAJHpdrUXrm4nfyMqceePLgvRAF91ulTRd_Aomt11GE4HY4tLCwbV2BsvO4-TYL1bTglqU?stp=s256x144&ccb=10-5&oh=00_AfClFoSM7hE45oIx-2m-KhoKQSiQLG9p0SE-g7jAUX_WNQ&oe=64CB1005&_nc_sid=201bca,8.666100,0,Waitangi,NZ,3,0.608575,1,15,14,0.000836
3,3,979252696029,afnhMrL1XClP80eDyubVWG,-43.821282,-176.482483,1662728350705,87.714785,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8_yqm62DeP3iQzc4rmEPO45gx3PhyrYSdvbVgDCpx7HHpM0xLWg8O_POUyzbf8L_vAFHBMvh2tiOetGaaQ15oQgfiI0rTKwhtgyvTtyDzH8w-wkKBIEivxxrtZB5GGc9dJvvUUO5prEvF3cfGm3fY?ccb=10-5&oh=00_AfA8S4Yle6dVFORPEr_l_zwYzCeRO3ruL1KmZ9DW5VJyFw&oe=64CB07C9&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8_yqm62DeP3iQzc4rmEPO45gx3PhyrYSdvbVgDCpx7HHpM0xLWg8O_POUyzbf8L_vAFHBMvh2tiOetGaaQ15oQgfiI0rTKwhtgyvTtyDzH8w-wkKBIEivxxrtZB5GGc9dJvvUUO5prEvF3cfGm3fY?stp=s256x144&ccb=10-5&oh=00_AfC2fnmhH-onM2BaognyNwZR_4peIfInSKJWWZuDSB9UHA&oe=64CB07C9&_nc_sid=201bca,53.907566,0,Waitangi,NZ,3,0.608575,1,15,14,0.000842
4,4,979252696411,uomscyCDp0Or1n42wRjAH8,-43.796436,-176.353881,1652259037804,279.000000,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8GAgAN8Esyz_z042XdvorAqdpSdHMjbfu10HaGemUU8OfN3V6SqYY3qA3w7nB6OpvfnO9j35gnWvzyvG00O1zILxSfHrhmKyml0UlEGRmW4I_pq35_pUpNOq8NSRYdJKDg91q_rg7mc5MWTZTBrwU?ccb=10-5&oh=00_AfDttaCQSIiL76h_UU_rDYonLAPD5ym9Hh66txO2zpSxwQ&oe=64CAFF67&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An8GAgAN8Esyz_z042XdvorAqdpSdHMjbfu10HaGemUU8OfN3V6SqYY3qA3w7nB6OpvfnO9j35gnWvzyvG00O1zILxSfHrhmKyml0UlEGRmW4I_pq35_pUpNOq8NSRYdJKDg91q_rg7mc5MWTZTBrwU?stp=s256x144&ccb=10-5&oh=00_AfBkNg63a_xQ3oeFX62As1eDq45aXky-ssFBjqzd144O4Q&oe=64CAFF67&_nc_sid=201bca,24.642113,0,Waitangi,NZ,3,0.608575,1,15,14,0.001403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46949,46949,2241972930422,CyDH857Zi0EvSNWmlruO6e,68.751297,92.115783,1658860830006,137.101372,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9-h0jhLKz3w0W3BNs6bxZueOXAr_t7HXAWb4y2uwM6T_HhHriAn6vxpYyK59Dx8qR58Ck9tf45kUnbvjftlb-ym2wraPgtru9UavQ3ZmZmfq-bot_v0QrGMbaQvsPsy05Wn1iZVOc7YbKEewAfog?ccb=10-5&oh=00_AfAc0Q9JrZdOQyn7Czb617g_TyznQBZVnRI5GATVzO0arw&oe=64C21158&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9-h0jhLKz3w0W3BNs6bxZueOXAr_t7HXAWb4y2uwM6T_HhHriAn6vxpYyK59Dx8qR58Ck9tf45kUnbvjftlb-ym2wraPgtru9UavQ3ZmZmfq-bot_v0QrGMbaQvsPsy05Wn1iZVOc7YbKEewAfog?stp=s256x192&ccb=10-5&oh=00_AfCw0E1DDStKUwP3inRu7yRaOCp4ldSJx_u9oCbtGlDH4g&oe=64C21158&_nc_sid=201bca,0.463913,332,Talnakh,RU,3,0.203509,0,27,9,0.207077
46950,46950,2241972930030,RLkawANjZhxQYlg5OUTmEC,69.313027,91.962320,1658047182000,50.000000,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An_beCqbTb5uLLzEkzTBmw0p93rxZ9Bm-H5ZSNSp77PPutl18em9wU_ihx5nHEJvqlppfRQBUhRzO8-sazNb0lWsDSsM5oX_tgaZdwBsAHTU5MDRWdVqKyOYSeQjFuniWMQ97rtLuAKyrvZDScw9xw?ccb=10-5&oh=00_AfBQ_4elAGcfuMgrZySUwIbYQNU6548vEnZz61PsikNHfQ&oe=64C1EF70&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An_beCqbTb5uLLzEkzTBmw0p93rxZ9Bm-H5ZSNSp77PPutl18em9wU_ihx5nHEJvqlppfRQBUhRzO8-sazNb0lWsDSsM5oX_tgaZdwBsAHTU5MDRWdVqKyOYSeQjFuniWMQ97rtLuAKyrvZDScw9xw?stp=s256x170&ccb=10-5&oh=00_AfAb5GhIqMRF3biggnAUj6lYcMwqkT49xb_6NigeFJZVBA&oe=64C1EF70&_nc_sid=201bca,0.000000,332,Talnakh,RU,3,0.203509,0,27,9,0.204454
46951,46951,2241972930852,ja0tKJihPy7D95CMY3qvxw,68.416126,93.876107,1659352384000,150.000000,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9tWNf9l4NYSYlw0zX10_U8fuu369TK2QFxW6ScYt_Tb66Fivg7IOaiH_xeEpCepZnca0EVlyLgQag4xqs6sW2i2sqtEK39OROEWcudl_0YY1OfRl5C0dUNd20zgl_FuxLR7HEns0ekeyXQvRuSpA?ccb=10-5&oh=00_AfC8c2zZi2RVBGXepOOXC9UdgsxwyMkUJDFzxJJi4-zB4A&oe=64C21DB3&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9tWNf9l4NYSYlw0zX10_U8fuu369TK2QFxW6ScYt_Tb66Fivg7IOaiH_xeEpCepZnca0EVlyLgQag4xqs6sW2i2sqtEK39OROEWcudl_0YY1OfRl5C0dUNd20zgl_FuxLR7HEns0ekeyXQvRuSpA?stp=s256x170&ccb=10-5&oh=00_AfB0MpjHIWs8SS_BKePSGowItV8OWwI4kvPa7HNUv3nVFA&oe=64C21DB3&_nc_sid=201bca,0.000000,332,Talnakh,RU,4,0.203509,0,27,12,0.257613
46952,46952,2241972931117,tYpcCPMrSNw1ZXEeHOgW5I,68.971124,92.634027,1658515124846,60.116845,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9Jb0xuL13DGH-Fl6M5Yb5PYGvXBo3KtVs1n1PYta2INNcwzfqE73mxCEPOGkwssUQYzw-D0P_20drAM9bXND_0Eze-356o4-BYeXb4P-sUjYxre5YiAWyzlK7Bzv2v7_YA6iobTiNh2rCMv5tksQ?ccb=10-5&oh=00_AfAwLbOXBPvQjFTM44_LoDxhCMn1n-S0qckM9TCByaQaNw&oe=64C1EDA5&_nc_sid=201bca,https://scontent-mrs2-1.xx.fbcdn.net/m1/v/t6/An9Jb0xuL13DGH-Fl6M5Yb5PYGvXBo3KtVs1n1PYta2INNcwzfqE73mxCEPOGkwssUQYzw-D0P_20drAM9bXND_0Eze-356o4-BYeXb4P-sUjYxre5YiAWyzlK7Bzv2v7_YA6iobTiNh2rCMv5tksQ?stp=s256x192&ccb=10-5&oh=00_AfCfDzaNlsjDSnpLuShhdh9R1B3F-F1IgUzW758MOuHLoA&oe=64C1EDA5&_nc_sid=201bca,2.222614,332,Talnakh,RU,9,0.203509,0,29,0,0.227805
46953,46953,3899830409746,7OZNuysahjvWEpBb8JlA9d,69.484265,147.286035,1634091916938,27.960319,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/An-eYKN_51ssLgbZ2tXMjHMapqLxFNaKTYtmv-goff-u933XwcVF53z6C06Doir7x7_2ROwayiu_Y27qDFs1zzdMOD0Z1e766gEJAe78SfiJvNKYMoti6Rt_SQm9uqUUlOzvQlzWc98Q9Z9xb_16Hg?ccb=10-5&oh=00_AfCJAtdd8y1aFIG24rLk1xDvENXiinqx51OOZ--9PXZvHQ&oe=64C4DA7F&_nc_sid=201bca,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/An-eYKN_51ssLgbZ2tXMjHMapqLxFNaKTYtmv-goff-u933XwcVF53z6C06Doir7x7_2ROwayiu_Y27qDFs1zzdMOD0Z1e766gEJAe78SfiJvNKYMoti6Rt_SQm9uqUUlOzvQlzWc98Q9Z9xb_16Hg?stp=s256x144&ccb=10-5&oh=00_AfCTEKEYAOl-9y_tfAhfsUR4EaEp_pLaoOKtOdmDR1xpBw&oe=64C4DA7F&_nc_sid=201bca,0.283128,333,Chokurdakh,RU,9,0.203509,0,27,9,0.096426

In [291]:
train.columns

Index(['id', 'sequence', 'latitude', 'longitude', 'captured_at',
       'computed_compass_angle', 'thumb_original_url', 'thumb_256_url',
       'speed', 'category', 'city', 'country', 'land_cover', 'road_index',
       'drive_side', 'climate', 'soil', 'dist_sea'],
      dtype='object')

In [1]:

import json
import os

from datetime import datetime

import geopandas as gpd
import numpy as np
import pandas as pd
import torch
import torch.utils.data as data
from scipy.interpolate import interp1d
from torch.nn import functional as F


class PASTIS_Dataset_PixelSet(data.Dataset):
    def __init__(
            self,
            folder,
            norm=True,
            cache=False,
            sats=["S2"],
            reference_date="2018-09-01",
            n_pixel=32,
            geom_features=True,
            folds=None,
            ignore_label=None,
            label_offset=1,
            class_mapping=None,
            interpolate=False,
            drop_temp_s2=0,
            drop_temp_s1=0,
    ):
        """
        Pytorch Dataset class to load samples from the PASTIS-R dataset in pixel-set
        format for parcel-based classification.

        The Dataset yields a data dictionary for each sample.
        For example, assuming the dataset was set to load
        Sentinel-2 observations (sats=['S2']),
        it will have the following keys:
            'S2': A tuple containing the Sentinel-2 time series of pixel-sets and
                the mask of true and repeated pixels. Formally, this key contains
                a tuple (X, M) with X a tensor of shape T_s2 x C_s2 x n_pixel and
                M a tensor of shape n_pixel. (T: number of available observations for S2,
                and C: number of spectral channels of S2)
            'dates-S2': A tensor containing the T dates of observation of the loaded
                S2 sequence. The dates are expressed as number of days since the
                reference date.
            'geomfeat' : A vector containing the parcel's 4 geometric features used
                by the Pixel-Set Encoder.
            'label' : Crop type label of the parcel.

        Args:
            folder (str): Path to the dataset
            norm (bool): If true, images are standardised using pre-computed
                channel-wise means and standard deviations.
            cache (bool): If True, the loaded samples stay in RAM, default False.
            sats (list): defines the satellites to use. In PASTIS-R you have access to
                Sentinel-2 imagery and Sentinel-1 observations in Ascending and Descending orbits,
                respectively S2, S1A, and S1D.
                For example use sats=['S2', 'S1A'] for Sentinel-2 + Sentinel-1 ascending time series,
                or sats=['S2', 'S1A','S1D'] to retrieve all time series.
                If you are using PASTIS, only  S2 observations are available.
            reference_date (str, Format : 'YYYY-MM-DD'): Defines the reference date
                based on which all observation dates are expressed. Along with the image
                time series and the target tensor, this dataloader yields the sequence
                of observation dates (in terms of number of days since the reference
                date). This sequence of dates is used for instance for the positional
                encoding in attention based approaches.
            n_pixel (int): number of pixels randomly sampled from each parcel (default 32).,
                geom_features (bool): If False no geometric descriptors of the parcel's shape
                are used in the Pixel-Set Encoder (default True).
            folds (list, optional): List of ints specifying which of the 5 official
                folds to load. By default (when None is specified) all folds are loaded.
            ignore_label (int): If not None, the parcels annotated with this label are discarded from
                the dataset.
            label_offset (int): If not None this offset is substracted from the labels contained in the dataset
                (default to 1 because PASTIS crop type labels start at 1).
            class_mapping (dict, optional): Dictionary to define a mapping between the
                default 18 class nomenclature and another class grouping, optional.
            interpolate (bool): if True, the Sentinel-1 observations are temporally interpolated to the
                dates of Sentinel-2 acquisitions (default False).
            drop_temp_s2 (float): probability of temporal dropout for Sentinel-2 time series (default 0.0),
            drop_temp_s1: probability of temporal dropout for Sentinel-1 time series (default 0.0),
        """
        assert sum([s in {"S1A", "S1D", "S2"} for s in sats]) == len(
            sats
        ), "Unknown satellite name (available: S2/S1A/S1D)"

        super(PASTIS_Dataset_PixelSet, self).__init__()
        self.folder = folder
        self.sats = sats
        self.norm = norm
        self.n_pixel = n_pixel
        self.geom_features = geom_features
        self.reference_date = datetime(*map(int, reference_date.split("-")))
        self.label_offset = label_offset
        self.cache = cache
        self.memory = {}
        self.memory_dates = {}
        self.class_mapping = class_mapping
        self.interpolate = interpolate
        self.drop_temp_s2 = drop_temp_s2
        self.drop_temp_s1 = drop_temp_s1

        # Get metadata
        print("Reading parcel metadata . . .")
        self.meta = pd.read_csv(os.path.join(folder, "metadata_parcel.csv"))
        self.meta.index = self.meta["ID_PARCEL"].astype(int)
        self.meta_patch = gpd.read_file(os.path.join(folder, "metadata.geojson"))
        self.meta_patch.index = self.meta_patch["ID_PATCH"].astype(int)
        self.meta_patch.sort_index(inplace=True)

        self.date_tables = {s: None for s in sats}
        self.date_range = np.array(range(-200, 600))
        for s in sats:
            dates = self.meta_patch["dates-{}".format(s)]
            date_table = pd.DataFrame(
                index=self.meta_patch.index, columns=self.date_range, dtype=int
            )
            for pid, date_seq in dates.items():
                d = pd.DataFrame().from_dict(date_seq, orient="index")
                d = d[0].apply(
                    lambda x: (
                            datetime(int(str(x)[:4]), int(str(x)[4:6]), int(str(x)[6:]))
                            - self.reference_date
                    ).days
                )
                date_table.loc[pid, d.values] = 1
            date_table = date_table.fillna(0)
            self.date_tables[s] = {
                index: np.array(list(d.values()))
                for index, d in date_table.to_dict(orient="index").items()
            }

        print("Done.")

        # Select Fold samples
        if folds is not None:
            self.meta = pd.concat([self.meta[self.meta["Fold"] == f] for f in folds])
        # Remove unwanted parcels
        if ignore_label is not None:
            self.meta = self.meta[self.meta["Label"] != ignore_label]

        self.meta.sort_index(inplace=True)
        self.len = self.meta.shape[0]
        self.id_parcels = self.meta.index
        self.labels = self.meta["Label"].to_dict()
        self.id_patches = self.meta["ID_PATCH"].to_dict()

        # Get normalisation values
        if norm:
            self.norm = {}
            for s in self.sats:
                with open(
                        os.path.join(folder, "NORM_PARCEL_{}_set.json".format(s)), "r"
                ) as file:
                    normvals = json.loads(file.read())
                selected_folds = folds if folds is not None else range(1, 6)
                means = [normvals["Fold_{}".format(f)]["mean"] for f in selected_folds]
                stds = [normvals["Fold_{}".format(f)]["std"] for f in selected_folds]
                self.norm[s] = np.stack(means).mean(axis=0), np.stack(stds).mean(axis=0)
                self.norm[s] = (
                    torch.from_numpy(self.norm[s][0]).float(),
                    torch.from_numpy(self.norm[s][1]).float(),
                )
        else:
            self.norm = {s: None for s in sats}

        # Prepare geometric features and their normalisation values for pixel-set
        if geom_features:
            print("Getting geometric features . . .")
            self.geomfeat = self.meta[[k for k in self.meta.columns if "GF_" in k]]
            self.geom_m, self.geom_s = (
                self.geomfeat.mean(axis=0).values,
                self.geomfeat.std(axis=0).values,
            )
            self.geomfeat = {
                index: np.array(list(d.values()))
                for index, d in self.geomfeat.to_dict(orient="index").items()
            }

        print("Dataset ready.")

    def __len__(self):
        return self.len

    def get_dates(self, id_patch, sat):
        return self.date_range[np.where(self.date_tables[sat][id_patch] == 1)[0]]

    def __getitem__(self, item):
        id_parcel = self.id_parcels[item]
        id_patch = self.id_patches[id_parcel]

        # Retrieve and prepare satellite data
        if not self.cache or item not in self.memory.keys():
            data = {
                satellite: np.load(
                    os.path.join(
                        self.folder,
                        "DATA_{}".format(satellite),
                        "{}_{}.npy".format(satellite, id_parcel),
                    )
                ).astype(np.float32)
                for satellite in self.sats
            }  # T x C x H x W arrays
            data = {s: torch.from_numpy(a) for s, a in data.items()}
            data = {
                s: repeat_pixel_and_norm(a, self.n_pixel, norm=self.norm[s])
                for s, a in data.items()
            }

            if self.cache:
                self.memory[item] = data

        else:
            data = self.memory[item]

        data = {
            sat: (sample_pixels(tensor, self.n_pixel), mask)
            for sat, (tensor, mask) in data.items()
        }  # Random pixel sampling

        # Retrieve date sequences
        if not self.cache or id_patch not in self.memory_dates.keys():
            dates = {
                "dates-{}".format(s): torch.from_numpy(self.get_dates(id_patch, s))
                for s in self.sats
            }
            if self.cache:
                self.memory_dates[id_patch] = dates
        else:
            dates = self.memory_dates[id_patch]

        # Temporal dropout
        if self.drop_temp_s1 + self.drop_temp_s2 > 0:
            selected_dates = {}
            for sat in self.sats:
                if "S1" in sat:
                    selected_dates[sat] = (
                            np.random.rand(data[sat][0].shape[0]) > self.drop_temp_s1
                    )
                elif "S2" in sat:
                    selected_dates[sat] = (
                            np.random.rand(data["S2"][0].shape[0]) > self.drop_temp_s2
                    )
            data = {sat: (d[0][selected_dates[sat]], d[1]) for sat, d in data.items()}
            dates = {s: d[selected_dates[s.split("-")[1]]] for s, d in dates.items()}

        data.update(dates)

        if self.interpolate and len(self.sats) > 1:
            for sat in self.sats:
                if sat == "S2":
                    continue
                interpolation = interp1d(
                    data["dates-{}".format(sat)].numpy(),
                    data[sat][0].numpy(),
                    axis=0,
                    fill_value="extrapolate",
                )
                data[sat] = (
                    torch.from_numpy(interpolation(data["dates-S2"].numpy())).float(),
                    data[sat][1],
                )
                data["dates-{}".format(sat)] = data["dates-S2"]

        # Retrieve label
        label = self.labels[id_parcel]
        if self.class_mapping is not None:
            label = self.class_mapping[label]
        data["label"] = torch.from_numpy(np.array(label - self.label_offset, dtype=int))

        # Retrieve geometric features
        if self.geom_features:
            gf = (self.geomfeat[id_parcel] - self.geom_m) / self.geom_s
            data["geomfeat"] = torch.from_numpy(gf).float()

        return data


def repeat_pixel_and_norm(pixels, n_pixel, norm=None):
    """
    Repeats a pixel if the parcel has fewer pixels than n_pixel.
    Normalises the channels.
    """
    if pixels.shape[-1] < n_pixel:
        if pixels.shape[-1] == 0:
            x = torch.zeros((*pixels.shape[:2], n_pixel))
            mask = np.array([0 for _ in range(n_pixel)])
            mask[0] = 1
        else:
            x = F.pad(pixels, [0, n_pixel - pixels.shape[-1]], mode="replicate")
            mask = np.array(
                [1 for _ in range(pixels.shape[-1])]
                + [0 for _ in range(pixels.shape[-1], n_pixel)]
            )
    else:
        x = pixels
        mask = np.array([1 for _ in range(n_pixel)])

    if norm is not None:
        m, s = norm
        x = (x - m[None, :, None]) / s[None, :, None]  # channelwise normalisation

    return (x, torch.from_numpy(mask))


def sample_pixels(pixels, n_pixel):
    """
    Random sampling of pixels within a parcel.
    """
    if pixels.shape[-1] > n_pixel:
        idx = np.random.choice(
            list(range(pixels.shape[-1])), size=n_pixel, replace=False
        )
        x = pixels[:, :, idx]
    else:
        x = pixels
    return x


def prepare_dates(date_dict, reference_date):
    """Transforms date of observation to number of days since
    the reference date.
    """
    d = pd.DataFrame().from_dict(date_dict, orient="index")
    d = d[0].apply(
        lambda x: (
                datetime(int(str(x)[:4]), int(str(x)[4:6]), int(str(x)[6:]))
                - reference_date
        ).days
    )
    return d.values

In [2]:
u = PASTIS_Dataset_PixelSet('/home/GAstruc/PhD/PhD/data/PASTIS-R_PixelSet', n_pixel=32, sats=['S2','S1A','S1D'])

Reading parcel metadata . . .
Done.
Getting geometric features . . .
Dataset ready.

In [3]:
len(u)

85951

In [4]:
def pad_tensor(x, l, pad_value=0):
    padlen = l - x.shape[0]
    pad = [0 for _ in range(2 * len(x.shape[1:]))] + [0, padlen]
    return F.pad(x, pad=pad, value=pad_value)


#np_str_obj_array_pattern = re.compile(r"[SaUO]")


def pad_collate(batch, pad_value=0):
    # Utility function to be used as collate_fn for the PyTorch dataloader
    # to handle sequences of varying length.
    # Sequences are padded with zeros by default.
    #
    # Modified default_collate from the official pytorch repo
    # https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py
    elem = batch[0]
    elem_type = type(elem)
    if isinstance(elem, torch.Tensor):
        out = None
        if len(elem.shape) > 0:
            sizes = [e.shape[0] for e in batch]
            m = max(sizes)
            if not all(s == m for s in sizes):
                # pad tensors which have a temporal dimension
                batch = [pad_tensor(e, m, pad_value=pad_value) for e in batch]
        if torch.utils.data.get_worker_info() is not None:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum([x.numel() for x in batch])
            storage = elem.storage()._new_shared(numel)
            out = elem.new(storage)
        return torch.stack(batch, 0, out=out)
    elif (
        elem_type.__module__ == "numpy"
        and elem_type.__name__ != "str_"
        and elem_type.__name__ != "string_"
    ):
        if elem_type.__name__ == "ndarray" or elem_type.__name__ == "memmap":
            # array of string classes and object
            if np_str_obj_array_pattern.search(elem.dtype.str) is not None:
                raise TypeError("Format not managed : {}".format(elem.dtype))

            return pad_collate([torch.as_tensor(b) for b in batch])
        elif elem.shape == ():  # scalars
            return torch.as_tensor(batch)

    elif isinstance(elem, collections.abc.Mapping):
        return {key: pad_collate([d[key] for d in batch]) for key in elem}

    elif isinstance(elem, tuple) and hasattr(elem, "_fields"):  # namedtuple
        return elem_type(*(pad_collate(samples) for samples in zip(*batch)))

    elif isinstance(elem, collections.abc.Sequence):
        # check to make sure that the elements in batch have consistent size
        it = iter(batch)
        elem_size = len(next(it))
        if not all(len(elem) == elem_size for elem in it):
            raise RuntimeError("each element in list of batch should be of equal size")
        transposed = zip(*batch)
        return [pad_collate(samples) for samples in transposed]

    raise TypeError("Format not managed : {}".format(elem_type))

In [5]:
from sklearn.model_selection import train_test_split

def get_loaders(dt, split, batch_size, num_workers):
    indices = list(range(len(dt)))
    np.random.shuffle(indices)

    X_inter, X_test = train_test_split(indices, test_size=split)

    X_train, X_val = train_test_split(X_inter, test_size=split)

    train_sampler = data.sampler.SubsetRandomSampler(X_train)
    validation_sampler = data.sampler.SubsetRandomSampler(X_val)
    test_sampler = data.sampler.SubsetRandomSampler(X_test)

    train_loader = data.DataLoader(dt, batch_size=batch_size,
                                    sampler=train_sampler,
                                    collate_fn=pad_collate,
                                    num_workers=num_workers)
    validation_loader = data.DataLoader(dt, batch_size=batch_size,
                                        sampler=validation_sampler,
                                        collate_fn=pad_collate,
                                        num_workers=num_workers)
    test_loader = data.DataLoader(dt, batch_size=batch_size,
                                    sampler=test_sampler,
                                    collate_fn=pad_collate,
                                    num_workers=num_workers)

    return(train_loader, validation_loader, test_loader)

In [8]:
import collections.abc

In [6]:
a, b, c = get_loaders(u, 0.2, 32, 1)

In [9]:
x = next(iter(a))

/tmp/ipykernel_349558/2700440532.py:31: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = elem.storage()._new_shared(numel)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [624640], which does not match the required output shape [32, 61, 10, 32]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [1024], which does not match the required output shape [32, 32]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [218112], which does not match the required output shape [32, 71, 3, 32]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [215040], which does not match the required output shape [32, 70, 3, 32]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [1952], which does not match the required output shape [32, 61]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [2272], which does not match the required output shape [32, 71]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [2240], which does not match the required output shape [32, 70]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)
/tmp/ipykernel_349558/2700440532.py:33: UserWarning: An output with one or more elements was resized since it had shape [128], which does not match the required output shape [32, 4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  return torch.stack(batch, 0, out=out)

In [10]:
x.keys()

dict_keys(['S2', 'S1A', 'S1D', 'dates-S2', 'dates-S1A', 'dates-S1D', 'label', 'geomfeat'])

In [12]:
max(x['label'])

tensor(15)

In [49]:
l = x['S1D']
l[0].shape

torch.Size([32, 70, 3, 32])

In [50]:
l = x['S1A']
l[0].shape

torch.Size([32, 71, 3, 32])

In [51]:
l = x['S2']
l[0].shape

torch.Size([32, 61, 10, 32])

In [129]:
import torch
import reverse_geocoder
import numpy as np
import pandas as pd


def haversine(pred, gt):
    # expects inputs to be np arrays in (lat, lon) format as radians
    # N x 2

    # calculate the difference in latitude and longitude between the predicted and ground truth points
    lat_diff = pred[:, 0] - gt[:, 0]
    lon_diff = pred[:, 1] - gt[:, 1]

    # calculate the haversine formula components
    lhs = torch.sin(lat_diff / 2) ** 2
    rhs = torch.cos(pred[:, 0]) * torch.cos(gt[:, 0]) * torch.sin(lon_diff / 2) ** 2
    a = lhs + rhs

    # calculate the final distance using the haversine formula
    c = 2 * torch.arctan2(torch.sqrt(a), torch.sqrt(1 - a))
    distance = 6371 * c

    return distance


def reverse(pred, gt, area):
    df = {}
    gt_area = {}
    nan_mask = {}
    areas = ["_".join(["unique", ar]) for ar in area]
    if "unique_continent" in areas:
        areas.remove("unique_continent")
    for ar in areas:
        inter = np.array(gt[ar])
        nan_mask[ar] = inter != "nan"
        gt_area[ar] = inter[nan_mask[ar]]
    location = reverse_geocoder.search(
        [
            (lat, lon)
            for lat, lon in zip(
                np.degrees(pred[:, 0].cpu()), np.degrees(pred[:, 1].cpu())
            )
        ]
    )
    if "continent" in area:
        continent = torch.load("/home/GAstruc/Téléchargements/continent.pt")
        continent['NA'] = 'Africa'
        inter = np.array([l.get("cc", "") for l in location])[
            nan_mask["unique_country"]
        ]
        df["continent"] = np.array([continent[i] for i in inter])
        gt_area["unique_continent"] = np.array(
            [continent[i] for i in gt_area["unique_country"]]
        )

    if "country" in area:
        df["country"] = np.array([l.get("cc", "") for l in location])[
            nan_mask["unique_country"]
        ]
    if "region" in area:
        df["region"] = np.array(
            ["_".join([l.get("admin1", ""), l.get("cc", "")]) for l in location]
        )[nan_mask["unique_region"]]
    if "sub-region" in area:
        df["sub-region"] = np.array(
            [
                "_".join([l.get("admin2", ""), l.get("admin1", ""), l.get("cc", "")])
                for l in location
            ]
        )[nan_mask["unique_sub-region"]]
    if "city" in area:
        df["city"] = np.array(
            [
                "_".join(
                    [
                        l.get("name", ""),
                        l.get("admin2", ""),
                        l.get("admin1", ""),
                        l.get("cc", ""),
                    ]
                )
                for l in location
            ]
        )[nan_mask["unique_city"]]

    return df, gt_area

In [158]:
df = pd.read_csv('/home/GAstruc/Téléchargements/select.csv')
df['quadtree_10_1000'] = [0 for i in range (len(df))]
df.to_csv('/home/GAstruc/Téléchargements/select.csv')

In [159]:
df.to_csv('/home/GAstruc/Téléchargements/select.csv')

In [83]:
df = pd.read_csv('/home/GAstruc/Téléchargements/select.csv')
df['gps'] = df[['longitude', 'latitude']].apply(lambda row: [np.radians(row['latitude']), np.radians(row['longitude'])], axis=1)
df = df.to_dict(orient='records')
gt = {key: [row[key] for row in df] for key in df[0].keys()}
gt['gps'] = torch.tensor(gt['gps'])

In [84]:
import os
u = os.listdir('/home/GAstruc/Downloads/results/')
fin = []
for i in u:
    if len(os.listdir('/home/GAstruc/Downloads/results/'+i)) == 51:
        fin.append(i)

In [138]:
geo = []
test = []
for i in fin:
    with open('/home/GAstruc/Downloads/results/'+ i + '/full.txt', 'r') as file:
        file_contents = file.read()
        if int(file_contents.split(' ')[2]) > 1900 or int(file_contents.split(' ')[2]) < 500:
            print(int(file_contents.split(' ')[2]))
        else:
            test.append(int(file_contents.split(' ')[2]))
            geo.append(i)

1974
4761
423
380
478
299

In [139]:
print(max(test))

1784

In [87]:
len(geo)

81

In [121]:
glob = []
for i in geo:
    preds = []
    for j in range(1, 51):
        with open('/home/GAstruc/Downloads/results/'+ i + '/' + f"{j:02}" + '.txt', 'r') as file:
            file_contents = file.read()
        preds.append([np.radians(float(file_contents.split(' ')[2][:-1])), np.radians(float(file_contents.split(' ')[3][:-1]))])
    pred = {'gps': torch.tensor(preds)}
    glob.append(pred)

In [122]:
len(glob)

80

In [173]:
oracle = [500000 for i in range (50)]
oracle_id = [0 for i in range (50)]
oracle_preds = torch.zeros((50,2))
dict = {"Geo": 0, "distance": 0}
acc_area = ["continent", "country", "region"]
save = []
for acc in acc_area:
    dict[f"Accuracy_{acc}"] = 0
j = 0
for pred in glob:
    j+=1
    haversine_distance = haversine(pred["gps"], gt["gps"])
    for i in range (len(haversine_distance)):
        save.append([gt['id'][i], gt['gps'][i], pred["gps"][i]])
        if haversine_distance[i] < oracle[i]:
            oracle_id[i] = j
            oracle[i] = haversine_distance[i]
            oracle_preds[i, :] = pred["gps"][i]
    if len(acc_area) > 0:
        area_pred, area_gt = reverse(pred["gps"], gt, acc_area)
    for acc in acc_area:
        dict[f"Accuracy_{acc}"] += (
            area_pred[acc] == area_gt["_".join(["unique", acc])]
        ).sum()/(len(area_gt["_".join(["unique", acc])])*len(glob))
    dict["distance"] += haversine_distance.sum()/(pred["gps"].shape[0]*len(glob))
    dict["Geo"] += 5000 * torch.exp(-haversine_distance / 1492.7).sum()/(pred["gps"].shape[0]*len(glob))

In [174]:
oracle_id

[58,
 36,
 65,
 28,
 6,
 27,
 62,
 6,
 12,
 2,
 66,
 8,
 76,
 6,
 65,
 24,
 62,
 77,
 52,
 8,
 43,
 22,
 76,
 70,
 39,
 46,
 9,
 75,
 27,
 32,
 63,
 63,
 47,
 61,
 1,
 31,
 18,
 35,
 50,
 42,
 62,
 31,
 23,
 65,
 58,
 7,
 58,
 48,
 58,
 35]

In [167]:
len(save)

4000

In [168]:
save[0]

[860133474581133,
 tensor([-0.5576,  2.0548], dtype=torch.float64),
 tensor([-0.5092,  0.3947], dtype=torch.float64)]

In [169]:
df = pd.DataFrame(save)

csv_file_path = 'result_human.csv'

# Save the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False, header=False)

In [131]:
dict

{'Geo': tensor(1008.8241, dtype=torch.float64),
 'distance': tensor(6407.1073, dtype=torch.float64),
 'Accuracy_continent': 0.4889999999999999,
 'Accuracy_country': 0.12150000000000008,
 'Accuracy_region': 0.03025000000000002}

In [171]:
haversine_distance

tensor([  93.4068,   31.2745,  165.1280,   96.2549,  322.2952,   33.8669,
         423.5364,  281.4838,  507.1639,  139.7976,  527.1085,  482.9172,
         199.9772,  191.9538,  838.1934, 1554.6101,   52.6402,  281.3438,
         260.6391,  192.1359, 3080.1881,  845.9512,  103.3267,  136.2819,
         103.7814,   60.9572,  177.7139,  594.8531,  222.0717,  513.7349,
          50.8207,   75.8122,  791.0584,   36.3636,  522.4626,  459.5747,
         816.6741,  107.1936,  609.7135,    9.1542,  210.0904,  280.1663,
        2305.9204, 1045.8113,  233.4971,  200.7868,  298.2200, 1230.7063,
         193.3585,  138.7220], dtype=torch.float64)

In [170]:
dict = {}
acc_area = ["continent", "country", "region"]
haversine_distance = haversine(oracle_preds, gt["gps"])
if len(acc_area) > 0:
    area_pred, area_gt = reverse(oracle_preds, gt, acc_area)
for acc in acc_area:
    dict[f"Accuracy_{acc}"] = (
        area_pred[acc] == area_gt["_".join(["unique", acc])]
    ).sum()/len(area_gt["_".join(["unique", acc])])
dict["distance"] = haversine_distance.sum()/oracle_preds.shape[0]
dict["Geo"] = 5000 * torch.exp(-haversine_distance / 1492.7).sum()/oracle_preds.shape[0]

In [133]:
dict

{'Accuracy_continent': 0.98,
 'Accuracy_country': 0.7,
 'Accuracy_region': 0.28,
 'distance': tensor(442.6139, dtype=torch.float64),
 'Geo': tensor(3918.9872, dtype=torch.float64)}

In [147]:
import random
import math

pred = {'gps': torch.tensor([[math.radians(random.uniform(-90, 90)), math.radians(random.uniform(-180, 180))] for i in range(50)])}

In [148]:
dict = {}
acc_area = ["continent", "country", "region"]
haversine_distance = haversine(pred['gps'], gt["gps"])
if len(acc_area) > 0:
    area_pred, area_gt = reverse(pred['gps'], gt, acc_area)
for acc in acc_area:
    dict[f"Accuracy_{acc}"] = (
        area_pred[acc] == area_gt["_".join(["unique", acc])]
    ).sum()/len(area_gt["_".join(["unique", acc])])
dict["distance"] = haversine_distance.sum()/oracle_preds.shape[0]
dict["Geo"] = 5000 * torch.exp(-haversine_distance / 1492.7).sum()/oracle_preds.shape[0]

In [149]:
dict

{'Accuracy_continent': 0.16,
 'Accuracy_country': 0.0,
 'Accuracy_region': 0.0,
 'distance': tensor(10262.6573, dtype=torch.float64),
 'Geo': tensor(119.7419, dtype=torch.float64)}

In [150]:
df = pd.read_csv('/home/GAstruc/train.csv')

/tmp/ipykernel_5560/2957875097.py:1: DtypeWarning: Columns (19,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/GAstruc/train.csv')

In [153]:
len(df)
np.randint(len(df))

AttributeError: module 'numpy' has no attribute 'randint'

In [154]:
pred = torch.zeros((50,2))
for i in range (50):
    h = random.randint(0, len(df) -1 )
    pred[i, :] = torch.tensor([np.radians(df['latitude'].iloc[h]), np.radians(df['longitude'].iloc[h])])

In [155]:
dict = {}
acc_area = ["continent", "country", "region"]
haversine_distance = haversine(pred, gt["gps"])
if len(acc_area) > 0:
    area_pred, area_gt = reverse(pred, gt, acc_area)
for acc in acc_area:
    dict[f"Accuracy_{acc}"] = (
        area_pred[acc] == area_gt["_".join(["unique", acc])]
    ).sum()/len(area_gt["_".join(["unique", acc])])
dict["distance"] = haversine_distance.sum()/oracle_preds.shape[0]
dict["Geo"] = 5000 * torch.exp(-haversine_distance / 1492.7).sum()/oracle_preds.shape[0]
dict

{'Accuracy_continent': 0.2,
 'Accuracy_country': 0.02,
 'Accuracy_region': 0.0,
 'distance': tensor(8723.6841, dtype=torch.float64),
 'Geo': tensor(327.7612, dtype=torch.float64)}

In [103]:
import pandas as pd
import numpy as np

In [104]:
test = pd.read_csv('/home/GAstruc/test.csv')

In [19]:
test['id']

0          547473234108938
1         1395174547521520
2          777072059643690
3         2969687633309946
4          369157591205593
                ...
485137     484916996261264
485138     947201369432368
485139     464095028024988
485140    3975075185917527
485141    4455441161137252
Name: id, Length: 485142, dtype: int64

In [20]:
test[test['id'] == 1020052598527653]

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
621,621,625,625,626,626,626,635,1020052598527653,42.988236,140.526845,...,9,0.0582,Hokkaido,NaN,Iwanai,Iwanai_NaN_Hokkaido_JP,NaN,Hokkaido_JP,JP,8187

In [119]:
u = pd.read_csv('/home/GAstruc/Downloads/positives.csv')

In [120]:
u[u['test_idx'] == 621]

Empty DataFrame
Columns: [test_idx, train_idx]
Index: []

In [121]:
i = np.unique(u['test_idx'])

In [95]:
test.iloc[i]

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
1,1,1,1,1,1,1,2,1395174547521520,52.213396,4.847324,...,9,0.286264,Utrecht,Gemeente De Ronde Venen,Mijdrecht,Mijdrecht_Gemeente De Ronde Venen_Utrecht_NL,Gemeente De Ronde Venen_Utrecht_NL,Utrecht_NL,NL,9311
2,2,2,2,2,2,2,3,777072059643690,2.230549,30.818912,...,10,1.000000,Northern Region,Zombo District,Paidha,Paidha_Zombo District_Northern Region_UG,Zombo District_Northern Region_UG,Northern Region_UG,UG,1556
3,3,3,3,3,3,3,4,2969687633309946,5.814546,-55.184531,...,5,0.175658,Paramaribo,NaN,Paramaribo,Paramaribo_NaN_Paramaribo_SR,NaN,Paramaribo_SR,SR,728
4,4,4,4,4,4,4,5,369157591205593,-25.284587,-57.499388,...,3,0.999967,Central,NaN,San Lorenzo,San Lorenzo_NaN_Central_PY,NaN,Central_PY,PY,203
5,5,5,5,5,5,5,6,2934069316850438,-36.350471,-71.860359,...,10,0.765177,Biobio,Provincia de Nuble,San Carlos,San Carlos_Provincia de Nuble_Biobio_CL,Provincia de Nuble_Biobio_CL,Biobio_CL,CL,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485133,485133,488498,488498,489955,489955,489955,499789,289539399329958,-19.534056,134.192917,...,11,0.999654,Northern Territory,Barkly,Tennant Creek,Tennant Creek_Barkly_Northern Territory_AU,Barkly_Northern Territory_AU,Northern Territory_AU,AU,1670
485134,485134,488499,488499,489956,489956,489956,499790,210462640586352,-36.293583,150.097194,...,14,0.012228,New South Wales,Eurobodalla,Narooma,Narooma_Eurobodalla_New South Wales_AU,Eurobodalla_New South Wales_AU,New South Wales_AU,AU,1190
485135,485135,488500,488500,489957,489957,489957,499791,481396596444046,44.630544,-93.508253,...,9,1.000000,Minnesota,Le Sueur County,New Prague,New Prague_Le Sueur County_Minnesota_US,Le Sueur County_Minnesota_US,Minnesota_US,US,3152
485137,485137,488502,488502,489959,489959,489959,499793,484916996261264,35.332649,134.827791,...,9,0.342928,Hyogo,NaN,Toyooka,Toyooka_NaN_Hyogo_JP,NaN,Hyogo_JP,JP,7916
485139,485139,488504,488504,489961,489961,489961,499795,464095028024988,15.533870,104.438844,...,9,0.928411,Amnat Charoen,NaN,Hua Taphan,Hua Taphan_NaN_Amnat Charoen_TH,NaN,Amnat Charoen_TH,TH,7502

In [30]:
i[-1]

485139

In [32]:
test.iloc[485139]

Unnamed: 0.6                                                     485139
Unnamed: 0.5                                                     488504
Unnamed: 0.4                                                     488504
Unnamed: 0.3                                                     489961
Unnamed: 0.2                                                     489961
Unnamed: 0.1                                                     489961
Unnamed: 0                                                       499795
id                                                      464095028024988
latitude                                                       15.53387
longitude                                                    104.438844
thumb_original_url    https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...
country                                                              TH
sequence                                         9g7jUxiERpmolEfCbVgZCQ
captured_at                                               1552966426908
lon_bin                                                              78
lat_bin                                                              52
cell                                                           (78, 52)
land_cover                                                            5
road_index                                                     4.260851
drive_side                                                            1
climate                                                               3
soil                                                                  9
dist_sea                                                       0.928411
region                                                    Amnat Charoen
sub-region                                                          NaN
city                                                         Hua Taphan
unique_city                             Hua Taphan_NaN_Amnat Charoen_TH
unique_sub-region                                                   NaN
unique_region                                          Amnat Charoen_TH
unique_country                                                       TH
quadtree_10_1000                                                   7502
Name: 485139, dtype: object

In [8]:
i

array([     1,      2,      3, ..., 485135, 485137, 485139])

In [10]:
df.drop(i)

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
0,0,0,0,0,0,0,1,547473234108938,-16.336027,45.628280,...,3,0.295011,Boeny,NaN,Sitampiky,Sitampiky_NaN_Boeny_MG,NaN,Boeny_MG,MG,1509
7,7,7,7,7,7,7,8,826109781317024,50.855687,56.147997,...,2,0.999849,Aqtoebe,NaN,Martuk,Martuk_NaN_Aqtoebe_KZ,NaN,Aqtoebe_KZ,KZ,10995
10,10,10,10,10,10,10,11,1006398440000844,37.956651,14.954485,...,9,0.227221,Sicily,Messina,Santa Domenica Vittoria,Santa Domenica Vittoria_Messina_Sicily_IT,Messina_Sicily_IT,Sicily_IT,IT,6488
11,11,11,11,11,11,11,12,2943891539215481,12.373333,-8.909906,...,11,0.999988,Koulikoro,NaN,Kangaba,Kangaba_NaN_Koulikoro_ML,NaN,Koulikoro_ML,ML,3362
13,13,13,13,13,13,13,14,122945119799579,7.510295,99.061884,...,14,0.002228,Krabi,NaN,Ko Lanta,Ko Lanta_NaN_Krabi_TH,NaN,Krabi_TH,TH,1804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485132,485132,488497,488497,489954,489954,489954,499788,311190247232610,-9.441765,160.093144,...,3,0.021378,Guadalcanal,NaN,Honiara,Honiara_NaN_Guadalcanal_SB,NaN,Guadalcanal_SB,SB,1769
485136,485136,488501,488501,489958,489958,489958,499792,333786891410519,38.885536,-86.035695,...,10,1.000000,Indiana,Jackson County,Brownstown,Brownstown_Jackson County_Indiana_US,Jackson County_Indiana_US,Indiana_US,US,3847
485138,485138,488503,488503,489960,489960,489960,499794,947201369432368,31.769290,-90.434008,...,9,0.914538,Mississippi,Copiah County,Wesson,Wesson_Copiah County_Mississippi_US,Copiah County_Mississippi_US,Mississippi_US,US,2395
485140,485140,488505,488505,489962,489962,489962,499796,3975075185917527,46.617128,-111.901360,...,9,1.000000,Montana,Lewis and Clark County,Helena Valley Southeast,Helena Valley Southeast_Lewis and Clark County...,Lewis and Clark County_Montana_US,Montana_US,US,5192
485141,485141,488506,488506,489963,489963,489963,499797,4455441161137252,-37.143860,145.082949,...,11,0.503568,Victoria,Murrindindi,Kinglake West,Kinglake West_Murrindindi_Victoria_AU,Murrindindi_Victoria_AU,Victoria_AU,AU,1122

In [12]:
df.drop(i).to_csv('/home/GAstruc/test_filtered.csv')

In [14]:
df = df.drop(i)

In [27]:
sum(i == 622)

1

In [21]:
df[df['id'] == 1020052598527653]

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
621,621,625,625,626,626,626,635,1020052598527653,42.988236,140.526845,...,9,0.0582,Hokkaido,NaN,Iwanai,Iwanai_NaN_Hokkaido_JP,NaN,Hokkaido_JP,JP,8187

In [22]:
train = pd.read_csv('/home/GAstruc/train.csv')
train[train['id'] == 291517332663378]

/tmp/ipykernel_5612/2364236903.py:1: DtypeWarning: Columns (19,35) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv('/home/GAstruc/train.csv')

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,...,quadtree_10_25000,quadtree_10_1000,quadtree_10_50000,quadtree_10_12500,quadtree_10_500,quadtree_10_2500,unique_region,unique_sub-region,unique_city,unique_country
3512176,3512176,3512176,2638290,2638290,2638290,2638290,2638290,2638290,291517332663378,42.982668,...,359,8187,195,786,12983,3896,Hokkaido_JP,NaN,Iwanai_NaN_Hokkaido_JP,JP

In [16]:
df

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
0,0,0,0,0,0,0,1,547473234108938,-16.336027,45.628280,...,3,0.295011,Boeny,NaN,Sitampiky,Sitampiky_NaN_Boeny_MG,NaN,Boeny_MG,MG,1509
7,7,7,7,7,7,7,8,826109781317024,50.855687,56.147997,...,2,0.999849,Aqtoebe,NaN,Martuk,Martuk_NaN_Aqtoebe_KZ,NaN,Aqtoebe_KZ,KZ,10995
10,10,10,10,10,10,10,11,1006398440000844,37.956651,14.954485,...,9,0.227221,Sicily,Messina,Santa Domenica Vittoria,Santa Domenica Vittoria_Messina_Sicily_IT,Messina_Sicily_IT,Sicily_IT,IT,6488
11,11,11,11,11,11,11,12,2943891539215481,12.373333,-8.909906,...,11,0.999988,Koulikoro,NaN,Kangaba,Kangaba_NaN_Koulikoro_ML,NaN,Koulikoro_ML,ML,3362
13,13,13,13,13,13,13,14,122945119799579,7.510295,99.061884,...,14,0.002228,Krabi,NaN,Ko Lanta,Ko Lanta_NaN_Krabi_TH,NaN,Krabi_TH,TH,1804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485132,485132,488497,488497,489954,489954,489954,499788,311190247232610,-9.441765,160.093144,...,3,0.021378,Guadalcanal,NaN,Honiara,Honiara_NaN_Guadalcanal_SB,NaN,Guadalcanal_SB,SB,1769
485136,485136,488501,488501,489958,489958,489958,499792,333786891410519,38.885536,-86.035695,...,10,1.000000,Indiana,Jackson County,Brownstown,Brownstown_Jackson County_Indiana_US,Jackson County_Indiana_US,Indiana_US,US,3847
485138,485138,488503,488503,489960,489960,489960,499794,947201369432368,31.769290,-90.434008,...,9,0.914538,Mississippi,Copiah County,Wesson,Wesson_Copiah County_Mississippi_US,Copiah County_Mississippi_US,Mississippi_US,US,2395
485140,485140,488505,488505,489962,489962,489962,499796,3975075185917527,46.617128,-111.901360,...,9,1.000000,Montana,Lewis and Clark County,Helena Valley Southeast,Helena Valley Southeast_Lewis and Clark County...,Lewis and Clark County_Montana_US,Montana_US,US,5192
485141,485141,488506,488506,489963,489963,489963,499797,4455441161137252,-37.143860,145.082949,...,11,0.503568,Victoria,Murrindindi,Kinglake West,Kinglake West_Murrindindi_Victoria_AU,Murrindindi_Victoria_AU,Victoria_AU,AU,1122

In [102]:
u = []
with open('/home/GAstruc/Downloads/collisions_1.txt', 'r') as file:
    # Read one line at a time
    file_contents = file.read()

In [110]:
u = []
for i in file_contents.split('\n'):
    u.append(int(i.split(' ')[0]))

ValueError: invalid literal for int() with base 10: ''

In [111]:
u[-1]

212616

In [106]:
len(file_contents.split('\n'))

2623

In [104]:
u[-1], file_contents.split('\n')[-2]

IndexError: list index out of range

In [54]:
df

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
0,0,0,0,0,0,0,1,547473234108938,-16.336027,45.628280,...,3,0.295011,Boeny,NaN,Sitampiky,Sitampiky_NaN_Boeny_MG,NaN,Boeny_MG,MG,1509
7,7,7,7,7,7,7,8,826109781317024,50.855687,56.147997,...,2,0.999849,Aqtoebe,NaN,Martuk,Martuk_NaN_Aqtoebe_KZ,NaN,Aqtoebe_KZ,KZ,10995
10,10,10,10,10,10,10,11,1006398440000844,37.956651,14.954485,...,9,0.227221,Sicily,Messina,Santa Domenica Vittoria,Santa Domenica Vittoria_Messina_Sicily_IT,Messina_Sicily_IT,Sicily_IT,IT,6488
11,11,11,11,11,11,11,12,2943891539215481,12.373333,-8.909906,...,11,0.999988,Koulikoro,NaN,Kangaba,Kangaba_NaN_Koulikoro_ML,NaN,Koulikoro_ML,ML,3362
13,13,13,13,13,13,13,14,122945119799579,7.510295,99.061884,...,14,0.002228,Krabi,NaN,Ko Lanta,Ko Lanta_NaN_Krabi_TH,NaN,Krabi_TH,TH,1804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485132,485132,488497,488497,489954,489954,489954,499788,311190247232610,-9.441765,160.093144,...,3,0.021378,Guadalcanal,NaN,Honiara,Honiara_NaN_Guadalcanal_SB,NaN,Guadalcanal_SB,SB,1769
485136,485136,488501,488501,489958,489958,489958,499792,333786891410519,38.885536,-86.035695,...,10,1.000000,Indiana,Jackson County,Brownstown,Brownstown_Jackson County_Indiana_US,Jackson County_Indiana_US,Indiana_US,US,3847
485138,485138,488503,488503,489960,489960,489960,499794,947201369432368,31.769290,-90.434008,...,9,0.914538,Mississippi,Copiah County,Wesson,Wesson_Copiah County_Mississippi_US,Copiah County_Mississippi_US,Mississippi_US,US,2395
485140,485140,488505,488505,489962,489962,489962,499796,3975075185917527,46.617128,-111.901360,...,9,1.000000,Montana,Lewis and Clark County,Helena Valley Southeast,Helena Valley Southeast_Lewis and Clark County...,Lewis and Clark County_Montana_US,Montana_US,US,5192
485141,485141,488506,488506,489963,489963,489963,499797,4455441161137252,-37.143860,145.082949,...,11,0.503568,Victoria,Murrindindi,Kinglake West,Kinglake West_Murrindindi_Victoria_AU,Murrindindi_Victoria_AU,Victoria_AU,AU,1122

In [56]:
filtered_df

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
0,0,0,0,0,0,0,1,547473234108938,-16.336027,45.628280,...,3,0.295011,Boeny,NaN,Sitampiky,Sitampiky_NaN_Boeny_MG,NaN,Boeny_MG,MG,1509
7,7,7,7,7,7,7,8,826109781317024,50.855687,56.147997,...,2,0.999849,Aqtoebe,NaN,Martuk,Martuk_NaN_Aqtoebe_KZ,NaN,Aqtoebe_KZ,KZ,10995
10,10,10,10,10,10,10,11,1006398440000844,37.956651,14.954485,...,9,0.227221,Sicily,Messina,Santa Domenica Vittoria,Santa Domenica Vittoria_Messina_Sicily_IT,Messina_Sicily_IT,Sicily_IT,IT,6488
11,11,11,11,11,11,11,12,2943891539215481,12.373333,-8.909906,...,11,0.999988,Koulikoro,NaN,Kangaba,Kangaba_NaN_Koulikoro_ML,NaN,Koulikoro_ML,ML,3362
13,13,13,13,13,13,13,14,122945119799579,7.510295,99.061884,...,14,0.002228,Krabi,NaN,Ko Lanta,Ko Lanta_NaN_Krabi_TH,NaN,Krabi_TH,TH,1804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485132,485132,488497,488497,489954,489954,489954,499788,311190247232610,-9.441765,160.093144,...,3,0.021378,Guadalcanal,NaN,Honiara,Honiara_NaN_Guadalcanal_SB,NaN,Guadalcanal_SB,SB,1769
485136,485136,488501,488501,489958,489958,489958,499792,333786891410519,38.885536,-86.035695,...,10,1.000000,Indiana,Jackson County,Brownstown,Brownstown_Jackson County_Indiana_US,Jackson County_Indiana_US,Indiana_US,US,3847
485138,485138,488503,488503,489960,489960,489960,499794,947201369432368,31.769290,-90.434008,...,9,0.914538,Mississippi,Copiah County,Wesson,Wesson_Copiah County_Mississippi_US,Copiah County_Mississippi_US,Mississippi_US,US,2395
485140,485140,488505,488505,489962,489962,489962,499796,3975075185917527,46.617128,-111.901360,...,9,1.000000,Montana,Lewis and Clark County,Helena Valley Southeast,Helena Valley Southeast_Lewis and Clark County...,Lewis and Clark County_Montana_US,Montana_US,US,5192
485141,485141,488506,488506,489963,489963,489963,499797,4455441161137252,-37.143860,145.082949,...,11,0.503568,Victoria,Murrindindi,Kinglake West,Kinglake West_Murrindindi_Victoria_AU,Murrindindi_Victoria_AU,Victoria_AU,AU,1122

In [105]:
# Create a boolean mask for rows to keep
mask = test['id'].isin(keep)

# Use boolean indexing to filter the DataFrame
filtered_df = test[mask]

In [113]:
final = filtered_df[['id', 'longitude', 'latitude', 'city', 'sub-region', 'region', 'country']]
final

,id,longitude,latitude,city,sub-region,region,country
15040,546314506564628,8.888875,39.559102,Sanluri,Provincia di Medio Campidano,Sardinia,IT
29361,296619375337754,118.323972,5.049666,Lahad Datu,NaN,Sabah,MY
32274,169782348369756,6.978765,31.429815,Hassi Messaoud,NaN,Ouargla,DZ
35025,4898606693529789,7.391129,6.441047,Enugu,NaN,Enugu,NG
42410,518332982744523,-39.857771,-14.010105,Jitauna,Jitauna,Bahia,BR
...,...,...,...,...,...,...,...
457148,393835759099320,36.808207,61.814915,Pudozh,NaN,Republic of Karelia,RU
467515,521919388810193,5.640525,45.830071,Virieu-le-Grand,Departement de l'Ain,Rhone-Alpes,FR
469302,434996004695363,-95.815308,36.003307,Broken Arrow,Tulsa County,Oklahoma,US
482902,2569566893353047,-76.533347,2.930462,Santander de Quilichao,NaN,Cauca,CO
483532,211450440452868,15.801577,61.496000,Edsbyn,Ovanakers Kommun,Gaevleborg,SE

In [127]:
res = pd.read_csv('/home/GAstruc/result_best.csv')
res.columns = ['nul', 'id', 'pred_lat_radians', 'pred_lon_radians', 'lat_radians', 'lon_radians']
res

,nul,id,pred_lat_radians,pred_lon_radians,lat_radians,lon_radians
0,0,547473234108938,"tensor(-0.2857, device='cuda:0', dtype=torch.f...","tensor(0.7940, device='cuda:0', dtype=torch.fl...","tensor(-0.2851, device='cuda:0')","tensor(0.7964, device='cuda:0')"
1,1,826109781317024,"tensor(0.8853, device='cuda:0', dtype=torch.fl...","tensor(1.0182, device='cuda:0', dtype=torch.fl...","tensor(0.8876, device='cuda:0')","tensor(0.9800, device='cuda:0')"
2,2,1006398440000844,"tensor(0.7609, device='cuda:0', dtype=torch.fl...","tensor(0.1934, device='cuda:0', dtype=torch.fl...","tensor(0.6625, device='cuda:0')","tensor(0.2610, device='cuda:0')"
3,3,2943891539215481,"tensor(0.2309, device='cuda:0', dtype=torch.fl...","tensor(-0.1359, device='cuda:0', dtype=torch.f...","tensor(0.2160, device='cuda:0')","tensor(-0.1555, device='cuda:0')"
4,4,122945119799579,"tensor(0.2151, device='cuda:0', dtype=torch.fl...","tensor(1.7872, device='cuda:0', dtype=torch.fl...","tensor(0.1311, device='cuda:0')","tensor(1.7290, device='cuda:0')"
...,...,...,...,...,...,...
210117,210117,311190247232610,"tensor(-0.1625, device='cuda:0', dtype=torch.f...","tensor(2.7733, device='cuda:0', dtype=torch.fl...","tensor(-0.1648, device='cuda:0')","tensor(2.7942, device='cuda:0')"
210118,210118,333786891410519,"tensor(0.6403, device='cuda:0', dtype=torch.fl...","tensor(-1.5963, device='cuda:0', dtype=torch.f...","tensor(0.6787, device='cuda:0')","tensor(-1.5016, device='cuda:0')"
210119,210119,947201369432368,"tensor(0.5658, device='cuda:0', dtype=torch.fl...","tensor(-1.6088, device='cuda:0', dtype=torch.f...","tensor(0.5545, device='cuda:0')","tensor(-1.5784, device='cuda:0')"
210120,210120,3975075185917527,"tensor(0.8124, device='cuda:0', dtype=torch.fl...","tensor(-1.9578, device='cuda:0', dtype=torch.f...","tensor(0.8136, device='cuda:0')","tensor(-1.9530, device='cuda:0')"
210121,210121,4455441161137252,"tensor(-0.6134, device='cuda:0', dtype=torch.f...","tensor(2.6061, device='cuda:0', dtype=torch.fl...","tensor(-0.6483, device='cuda:0')","tensor(2.5322, device='cuda:0')"

In [130]:
res

,nul,id,pred_lat_radians,pred_lon_radians,lat_radians,lon_radians
6844,6844,546314506564628,"tensor(0.7113, device='cuda:0', dtype=torch.fl...","tensor(0.2873, device='cuda:0', dtype=torch.fl...","tensor(0.6904, device='cuda:0')","tensor(0.1551, device='cuda:0')"
13268,13268,296619375337754,"tensor(0.0544, device='cuda:0', dtype=torch.fl...","tensor(1.7704, device='cuda:0', dtype=torch.fl...","tensor(0.0881, device='cuda:0')","tensor(2.0651, device='cuda:0')"
14620,14620,169782348369756,"tensor(0.6435, device='cuda:0', dtype=torch.fl...","tensor(-1.9880, device='cuda:0', dtype=torch.f...","tensor(0.5486, device='cuda:0')","tensor(0.1218, device='cuda:0')"
15812,15812,4898606693529789,"tensor(0.1148, device='cuda:0', dtype=torch.fl...","tensor(0.0577, device='cuda:0', dtype=torch.fl...","tensor(0.1124, device='cuda:0')","tensor(0.1290, device='cuda:0')"
19101,19101,518332982744523,"tensor(-0.2452, device='cuda:0', dtype=torch.f...","tensor(-0.6901, device='cuda:0', dtype=torch.f...","tensor(-0.2445, device='cuda:0')","tensor(-0.6956, device='cuda:0')"
...,...,...,...,...,...,...
198473,198473,393835759099320,"tensor(0.7435, device='cuda:0', dtype=torch.fl...","tensor(0.4323, device='cuda:0', dtype=torch.fl...","tensor(1.0789, device='cuda:0')","tensor(0.6424, device='cuda:0')"
202801,202801,521919388810193,"tensor(0.8011, device='cuda:0', dtype=torch.fl...","tensor(0.0975, device='cuda:0', dtype=torch.fl...","tensor(0.7999, device='cuda:0')","tensor(0.0984, device='cuda:0')"
203537,203537,434996004695363,"tensor(0.6292, device='cuda:0', dtype=torch.fl...","tensor(-1.6730, device='cuda:0', dtype=torch.f...","tensor(0.6284, device='cuda:0')","tensor(-1.6723, device='cuda:0')"
209192,209192,2569566893353047,"tensor(0.0493, device='cuda:0', dtype=torch.fl...","tensor(-1.3358, device='cuda:0', dtype=torch.f...","tensor(0.0511, device='cuda:0')","tensor(-1.3358, device='cuda:0')"
209471,209471,211450440452868,"tensor(1.0717, device='cuda:0', dtype=torch.fl...","tensor(0.2763, device='cuda:0', dtype=torch.fl...","tensor(1.0733, device='cuda:0')","tensor(0.2758, device='cuda:0')"

In [135]:
final['id'].iloc[0]

546314506564628

In [148]:
import re

li = []
col = "pred_lat_radians"

for i in range(len(res)):
    # Your input string
    input_string = res[res['id'] == final['id'].iloc[i]][col].iloc[0]

    # Use regular expression to extract the numerical value
    match = re.search(r'-?\d+\.\d+', input_string)

    # Check if a match is found
    if match:
        # Extract the matched value
        li.append(np.degrees(float(match.group())))

final["pred_latitude"] = li

/tmp/ipykernel_101288/3656843265.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["pred_latitude"] = li

In [150]:
final.to_csv('/home/GAstruc/select2.csv')

In [129]:
# Create a boolean mask for rows to keep
mask = res['id'].isin(keep)

# Use boolean indexing to filter the DataFrame
res = res[mask]

In [122]:
merged_df = pd.merge(final, res, on='id')

In [123]:
merged_df

,id,longitude,latitude,city,sub-region,region,country,nul,pred_lat,pred_lon,lat,lon
0,546314506564628,8.888875,39.559102,Sanluri,Provincia di Medio Campidano,Sardinia,IT,6844,"tensor(0.7113, device='cuda:0', dtype=torch.fl...","tensor(0.2873, device='cuda:0', dtype=torch.fl...","tensor(0.6904, device='cuda:0')","tensor(0.1551, device='cuda:0')"
1,296619375337754,118.323972,5.049666,Lahad Datu,NaN,Sabah,MY,13268,"tensor(0.0544, device='cuda:0', dtype=torch.fl...","tensor(1.7704, device='cuda:0', dtype=torch.fl...","tensor(0.0881, device='cuda:0')","tensor(2.0651, device='cuda:0')"
2,169782348369756,6.978765,31.429815,Hassi Messaoud,NaN,Ouargla,DZ,14620,"tensor(0.6435, device='cuda:0', dtype=torch.fl...","tensor(-1.9880, device='cuda:0', dtype=torch.f...","tensor(0.5486, device='cuda:0')","tensor(0.1218, device='cuda:0')"
3,4898606693529789,7.391129,6.441047,Enugu,NaN,Enugu,NG,15812,"tensor(0.1148, device='cuda:0', dtype=torch.fl...","tensor(0.0577, device='cuda:0', dtype=torch.fl...","tensor(0.1124, device='cuda:0')","tensor(0.1290, device='cuda:0')"
4,518332982744523,-39.857771,-14.010105,Jitauna,Jitauna,Bahia,BR,19101,"tensor(-0.2452, device='cuda:0', dtype=torch.f...","tensor(-0.6901, device='cuda:0', dtype=torch.f...","tensor(-0.2445, device='cuda:0')","tensor(-0.6956, device='cuda:0')"
...,...,...,...,...,...,...,...,...,...,...,...,...
66,393835759099320,36.808207,61.814915,Pudozh,NaN,Republic of Karelia,RU,198473,"tensor(0.7435, device='cuda:0', dtype=torch.fl...","tensor(0.4323, device='cuda:0', dtype=torch.fl...","tensor(1.0789, device='cuda:0')","tensor(0.6424, device='cuda:0')"
67,521919388810193,5.640525,45.830071,Virieu-le-Grand,Departement de l'Ain,Rhone-Alpes,FR,202801,"tensor(0.8011, device='cuda:0', dtype=torch.fl...","tensor(0.0975, device='cuda:0', dtype=torch.fl...","tensor(0.7999, device='cuda:0')","tensor(0.0984, device='cuda:0')"
68,434996004695363,-95.815308,36.003307,Broken Arrow,Tulsa County,Oklahoma,US,203537,"tensor(0.6292, device='cuda:0', dtype=torch.fl...","tensor(-1.6730, device='cuda:0', dtype=torch.f...","tensor(0.6284, device='cuda:0')","tensor(-1.6723, device='cuda:0')"
69,2569566893353047,-76.533347,2.930462,Santander de Quilichao,NaN,Cauca,CO,209192,"tensor(0.0493, device='cuda:0', dtype=torch.fl...","tensor(-1.3358, device='cuda:0', dtype=torch.f...","tensor(0.0511, device='cuda:0')","tensor(-1.3358, device='cuda:0')"
70,211450440452868,15.801577,61.496000,Edsbyn,Ovanakers Kommun,Gaevleborg,SE,209471,"tensor(1.0717, device='cuda:0', dtype=torch.fl...","tensor(0.2763, device='cuda:0', dtype=torch.fl...","tensor(1.0733, device='cuda:0')","tensor(0.2758, device='cuda:0')"

In [60]:
df.reset_index(drop=True).drop(u).to_csv('/home/GAstruc/test_filtered.csv')

In [159]:
select = pd.read_csv('/home/GAstruc/test_filtered.csv')

In [160]:
select

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
0,0,0,0,0,0,0,0,1,547473234108938,-16.336027,...,3,0.295011,Boeny,NaN,Sitampiky,Sitampiky_NaN_Boeny_MG,NaN,Boeny_MG,MG,1509
1,1,7,7,7,7,7,7,8,826109781317024,50.855687,...,2,0.999849,Aqtoebe,NaN,Martuk,Martuk_NaN_Aqtoebe_KZ,NaN,Aqtoebe_KZ,KZ,10995
2,2,10,10,10,10,10,10,11,1006398440000844,37.956651,...,9,0.227221,Sicily,Messina,Santa Domenica Vittoria,Santa Domenica Vittoria_Messina_Sicily_IT,Messina_Sicily_IT,Sicily_IT,IT,6488
3,3,11,11,11,11,11,11,12,2943891539215481,12.373333,...,11,0.999988,Koulikoro,NaN,Kangaba,Kangaba_NaN_Koulikoro_ML,NaN,Koulikoro_ML,ML,3362
4,4,13,13,13,13,13,13,14,122945119799579,7.510295,...,14,0.002228,Krabi,NaN,Ko Lanta,Ko Lanta_NaN_Krabi_TH,NaN,Krabi_TH,TH,1804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210117,212739,485132,488497,488497,489954,489954,489954,499788,311190247232610,-9.441765,...,3,0.021378,Guadalcanal,NaN,Honiara,Honiara_NaN_Guadalcanal_SB,NaN,Guadalcanal_SB,SB,1769
210118,212740,485136,488501,488501,489958,489958,489958,499792,333786891410519,38.885536,...,10,1.000000,Indiana,Jackson County,Brownstown,Brownstown_Jackson County_Indiana_US,Jackson County_Indiana_US,Indiana_US,US,3847
210119,212741,485138,488503,488503,489960,489960,489960,499794,947201369432368,31.769290,...,9,0.914538,Mississippi,Copiah County,Wesson,Wesson_Copiah County_Mississippi_US,Copiah County_Mississippi_US,Mississippi_US,US,2395
210120,212742,485140,488505,488505,489962,489962,489962,499796,3975075185917527,46.617128,...,9,1.000000,Montana,Lewis and Clark County,Helena Valley Southeast,Helena Valley Southeast_Lewis and Clark County...,Lewis and Clark County_Montana_US,Montana_US,US,5192
210121,212743,485141,488506,488506,489963,489963,489963,499797,4455441161137252,-37.143860,...,11,0.503568,Victoria,Murrindindi,Kinglake West,Kinglake West_Murrindindi_Victoria_AU,Murrindindi_Victoria_AU,Victoria_AU,AU,1122

In [ ]:
select['id']

In [96]:
test.iloc[i]

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,latitude,longitude,...,soil,dist_sea,region,sub-region,city,unique_city,unique_sub-region,unique_region,unique_country,quadtree_10_1000
1,1,1,1,1,1,1,2,1395174547521520,52.213396,4.847324,...,9,0.286264,Utrecht,Gemeente De Ronde Venen,Mijdrecht,Mijdrecht_Gemeente De Ronde Venen_Utrecht_NL,Gemeente De Ronde Venen_Utrecht_NL,Utrecht_NL,NL,9311
2,2,2,2,2,2,2,3,777072059643690,2.230549,30.818912,...,10,1.000000,Northern Region,Zombo District,Paidha,Paidha_Zombo District_Northern Region_UG,Zombo District_Northern Region_UG,Northern Region_UG,UG,1556
3,3,3,3,3,3,3,4,2969687633309946,5.814546,-55.184531,...,5,0.175658,Paramaribo,NaN,Paramaribo,Paramaribo_NaN_Paramaribo_SR,NaN,Paramaribo_SR,SR,728
4,4,4,4,4,4,4,5,369157591205593,-25.284587,-57.499388,...,3,0.999967,Central,NaN,San Lorenzo,San Lorenzo_NaN_Central_PY,NaN,Central_PY,PY,203
5,5,5,5,5,5,5,6,2934069316850438,-36.350471,-71.860359,...,10,0.765177,Biobio,Provincia de Nuble,San Carlos,San Carlos_Provincia de Nuble_Biobio_CL,Provincia de Nuble_Biobio_CL,Biobio_CL,CL,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485133,485133,488498,488498,489955,489955,489955,499789,289539399329958,-19.534056,134.192917,...,11,0.999654,Northern Territory,Barkly,Tennant Creek,Tennant Creek_Barkly_Northern Territory_AU,Barkly_Northern Territory_AU,Northern Territory_AU,AU,1670
485134,485134,488499,488499,489956,489956,489956,499790,210462640586352,-36.293583,150.097194,...,14,0.012228,New South Wales,Eurobodalla,Narooma,Narooma_Eurobodalla_New South Wales_AU,Eurobodalla_New South Wales_AU,New South Wales_AU,AU,1190
485135,485135,488500,488500,489957,489957,489957,499791,481396596444046,44.630544,-93.508253,...,9,1.000000,Minnesota,Le Sueur County,New Prague,New Prague_Le Sueur County_Minnesota_US,Le Sueur County_Minnesota_US,Minnesota_US,US,3152
485137,485137,488502,488502,489959,489959,489959,499793,484916996261264,35.332649,134.827791,...,9,0.342928,Hyogo,NaN,Toyooka,Toyooka_NaN_Hyogo_JP,NaN,Hyogo_JP,JP,7916
485139,485139,488504,488504,489961,489961,489961,499795,464095028024988,15.533870,104.438844,...,9,0.928411,Amnat Charoen,NaN,Hua Taphan,Hua Taphan_NaN_Amnat Charoen_TH,NaN,Amnat Charoen_TH,TH,7502

In [125]:
ids = list(test.iloc[i]['id'])

In [127]:
j = 0
v = []
for i in range (len(select)):
    if select['id'].iloc[i] in ids:
        print(select['id'].iloc[i])
        v.append(i)
        j+=1

152454737707008
184068376916582
311028890545710
1093560081172659
189829202981952
1389710078031039
769547813760817
303007251265953
320105042867850
304682731408847
169961348374774
141905757860376
917445892443616
859387714930005
2295166667284628
1441534879556156
213668066965052
491911438726571
228333062384255
339675071071472
1234836596948376
838797057047031
299535091653682

In [101]:
j

23

In [124]:
ids = list(test.iloc[u]['id'])

IndexError: DataFrame indexer is not allowed for .iloc
Consider using .loc for automatic alignment.

In [114]:
j = 0
for i in range (len(select)):
    if select['id'].iloc[i] in u:
        print(select['id'].iloc[i])
        j+=1

In [115]:
j

0

In [158]:
select.drop(v).to_csv('/home/GAstruc/Téléchargements/select2.csv')

In [108]:
res = pd.read_csv('/home/GAstruc/result_best.csv')

In [153]:
res.columns = ['id', 'gt', 'pred']

In [143]:
def haversine(pred, gt):
    # expects inputs to be np arrays in (lat, lon) format as radians
    # N x 2

    # calculate the difference in latitude and longitude between the predicted and ground truth points
    match = re.search(r'\[([^\]]+)\]', pred)
    content_between_brackets = match.group(1)
    pred = torch.tensor([float(content_between_brackets.split(',')[0]), float(content_between_brackets.split(',')[1])])
    match = re.search(r'\[([^\]]+)\]', gt)
    content_between_brackets = match.group(1)
    gt = torch.tensor([float(content_between_brackets.split(',')[0]), float(content_between_brackets.split(',')[1])])
    lat_diff = pred[0] - gt[0]
    lon_diff = pred[1] - gt[1]

    # calculate the haversine formula components
    lhs = torch.sin(lat_diff / 2) ** 2
    rhs = torch.cos(pred[0]) * torch.cos(gt[0]) * torch.sin(lon_diff / 2) ** 2
    a = lhs + rhs

    # calculate the final distance using the haversine formula
    c = 2 * torch.arctan2(torch.sqrt(a), torch.sqrt(1 - a))
    distance = 6371 * c

    return distance

In [111]:
res.iloc[0][2]

"tensor([-0.2857,  0.7940], device='cuda:0', dtype=torch.float64)"

In [154]:
dist= []
for i in range (len(res.iloc[v])):
    dist.append(haversine(res.iloc[v].iloc[i]['pred'], res.iloc[v].iloc[i]['gt']))

TypeError: expected string or bytes-like object

In [150]:
dist

[tensor(154.5423),
 tensor(5.8052),
 tensor(396.1959),
 tensor(18.3685),
 tensor(164.4981),
 tensor(17.1001),
 tensor(964.6017),
 tensor(626.4041),
 tensor(128.7008),
 tensor(1890.1090),
 tensor(14922.1250),
 tensor(72.4075),
 tensor(2111.1294),
 tensor(416.3762),
 tensor(122.0696),
 tensor(2744.0312),
 tensor(4.5649),
 tensor(181.5593),
 tensor(25.1808),
 tensor(10.7596),
 tensor(170.1997),
 tensor(25.3137),
 tensor(162.7135)]

In [67]:
file_path = '/home/GAstruc/Downloads/street-clip-unordered.txt'

# Open the file in read mode ('r' stands for read)
with open(file_path, 'r') as file:
    # Read the entire contents of the file
    file_contents = file.read().split('\n')[:-1]

In [68]:
ids, dists = [], []
for file in file_contents:
    ids.append(int(file.split(';')[0]))
    dists.append(float(file.split(';')[1]))

In [98]:
file_path = '/home/GAstruc/Downloads/select2.txt'
# Open the file in read mode ('r' stands for read)
with open(file_path, 'r') as file:
    # Read the entire contents of the file
    file_conts = file.read().split('\n')[:-1]

In [100]:
keep = [int(float(file)) for file in file_conts]

In [95]:
import numpy as np

ids_array = np.array(ids)
keep_set = np.array(keep)

# Find the indices where ids are in the keep set
indices_to_keep = np.where(np.isin(ids_array, keep_set))[0]

# Use the indices to extract the corresponding elements from dists
dist = np.array(dists)[indices_to_keep]

In [96]:
import torch

geo = 5000 * torch.exp(- torch.tensor(dist) / 1492.7).sum() / len(dist)

In [97]:
geo, dist.sum()/ len(dist)

(tensor(3296.4949, dtype=torch.float64), 1696.068446525047)

In [ ]:
path + split + "_filenames.lst"

In [160]:
import h5py

path = "/home/GAstruc/patches-dataset/"
file_path =  path + "Abies_alba_1_322558_BI_NLF_2017.h5"

# Open the HDF5 file in read-only mode
with h5py.File(file_path, 'r') as file:
    print("Keys at the root level:", list(file.keys()))
    data_S1_asc = file["sen-1-asc-data"][:]
    data_S2 = file["sen-2-data"][:]
    data_S1_des = file["sen-1-des-data"][:]

Keys at the root level: ['sen-1-asc-data', 'sen-1-asc-products', 'sen-1-des-data', 'sen-1-des-products', 'sen-2-data', 'sen-2-masks', 'sen-2-products']

In [161]:
data_S1_asc.shape, data_S2.shape, data_S1_des.shape

((121, 2, 6, 6), (48, 10, 6, 6), (120, 2, 6, 6))

In [1]:
with open("/home/GAstruc/PhD/PhD/data/TreeSat/train_filenames.lst", 'r') as file:
    lst_list = [line.strip() for line in file.readlines()]

with open("/home/GAstruc/PhD/PhD/data/TreeSat/val_filenames.lst", 'r') as file:
    lst_list += [line.strip() for line in file.readlines()]

with open("/home/GAstruc/PhD/PhD/data/TreeSat/test_filenames.lst", 'r') as file:
    lst_list += [line.strip() for line in file.readlines()]

# Print the resulting list
len(lst_list)

50374

In [2]:
import h5py

size_s1_asc, size_s1_des, size_s2 = [], [], []
for file in lst_list:
    with h5py.File('/home/GAstruc/PhD/PhD/data/TreeSat/' + "sentinel/" + '.'.join(file.split('.')[:-1]) + ".h5", 'r') as file:
        size_s1_asc.append(file["sen-1-asc-data"][:].shape[0])
        size_s1_des.append(file["sen-1-des-data"][:].shape[0])
        size_s2.append(file["sen-2-data"][:].shape[0])

In [16]:
with h5py.File('/home/GAstruc/PhD/PhD/data/TreeSat/' + "sentinel/" + '.'.join(lst_list[0].split('.')[:-1]) + ".h5", 'r') as file:
    print(file.keys())
    print(file['sen-2-products'][:])

<KeysViewHDF5 ['sen-1-asc-data', 'sen-1-asc-products', 'sen-1-des-data', 'sen-1-des-products', 'sen-2-data', 'sen-2-masks', 'sen-2-products']>
[b'S2A_MSIL2A_20200102T102421_N0213_R065_T32UNC_20200102T115419'
 b'S2A_MSIL2A_20200105T103421_N0213_R108_T32UNC_20200105T120935'
 b'S2B_MSIL2A_20200107T102319_N0213_R065_T32UNC_20200107T130248'
 b'S2B_MSIL2A_20200110T103319_N0213_R108_T32UNC_20200112T153344'
 b'S2A_MSIL2A_20200112T102401_N0213_R065_T32UNC_20200112T115112'
 b'S2A_MSIL2A_20200115T103401_N0213_R108_T32UNC_20200115T121049'
 b'S2B_MSIL2A_20200117T102249_N0213_R065_T32UNC_20200117T122813'
 b'S2B_MSIL2A_20200120T103239_N0213_R108_T32UNC_20200120T123240'
 b'S2A_MSIL2A_20200122T102321_N0213_R065_T32UNC_20200122T115556'
 b'S2A_MSIL2A_20200125T103321_N0213_R108_T32UNC_20200125T115803'
 b'S2B_MSIL2A_20200127T102209_N0213_R065_T32UNC_20200127T121956'
 b'S2B_MSIL2A_20200130T103159_N0213_R108_T32UNC_20200130T130812'
 b'S2A_MSIL2A_20200201T102241_N0213_R065_T32UNC_20200201T114938'
 b'S2A_MSIL2A_20200204T103221_N0214_R108_T32UNC_20200204T121112'
 b'S2B_MSIL2A_20200206T102109_N0214_R065_T32UNC_20200206T140634'
 b'S2B_MSIL2A_20200209T103059_N0214_R108_T32UNC_20200209T131157'
 b'S2A_MSIL2A_20200211T102141_N0214_R065_T32UNC_20200211T115801'
 b'S2A_MSIL2A_20200214T103121_N0214_R108_T32UNC_20200214T123037'
 b'S2B_MSIL2A_20200216T102019_N0214_R065_T32UNC_20200216T125714'
 b'S2B_MSIL2A_20200219T102949_N0214_R108_T32UNC_20200219T130154'
 b'S2A_MSIL2A_20200221T102041_N0214_R065_T32UNC_20200221T120618'
 b'S2A_MSIL2A_20200224T103021_N0214_R108_T32UNC_20200224T132853'
 b'S2B_MSIL2A_20200226T101909_N0214_R065_T32UNC_20200226T163348'
 b'S2B_MSIL2A_20200229T102849_N0214_R108_T32UNC_20200229T134938'
 b'S2A_MSIL2A_20200302T102021_N0214_R065_T32UNC_20200302T140838'
 b'S2A_MSIL2A_20200305T103021_N0214_R108_T32UNC_20200305T132101'
 b'S2B_MSIL2A_20200307T101759_N0214_R065_T32UNC_20200307T135934'
 b'S2B_MSIL2A_20200310T102739_N0214_R108_T32UNC_20200310T140512'
 b'S2A_MSIL2A_20200312T102021_N0214_R065_T32UNC_20200312T131221'
 b'S2A_MSIL2A_20200315T103021_N0214_R108_T32UNC_20200315T120702'
 b'S2B_MSIL2A_20200317T101649_N0214_R065_T32UNC_20200317T133647'
 b'S2B_MSIL2A_20200320T102639_N0214_R108_T32UNC_20200320T141657'
 b'S2A_MSIL2A_20200322T102021_N0214_R065_T32UNC_20200322T120506'
 b'S2A_MSIL2A_20200325T103021_N0214_R108_T32UNC_20200325T144818'
 b'S2B_MSIL2A_20200327T101629_N0214_R065_T32UNC_20200327T134849'
 b'S2B_MSIL2A_20200330T102609_N0214_R108_T32UNC_20200330T140254'
 b'S2A_MSIL2A_20200401T102021_N0214_R065_T32UNC_20200401T134905'
 b'S2A_MSIL2A_20200404T103021_N0214_R108_T32UNC_20200404T135955'
 b'S2B_MSIL2A_20200406T101559_N0214_R065_T32UNC_20200406T134514'
 b'S2B_MSIL2A_20200409T102559_N0214_R108_T32UNC_20200409T140105'
 b'S2A_MSIL2A_20200411T102021_N0214_R065_T32UNC_20200411T143032'
 b'S2A_MSIL2A_20200414T103021_N0214_R108_T32UNC_20200414T111546'
 b'S2B_MSIL2A_20200416T101549_N0214_R065_T32UNC_20200416T135611'
 b'S2B_MSIL2A_20200419T102549_N0214_R108_T32UNC_20200419T140808'
 b'S2A_MSIL2A_20200421T102021_N0214_R065_T32UNC_20200421T120142'
 b'S2A_MSIL2A_20200424T103021_N0214_R108_T32UNC_20200424T135824'
 b'S2B_MSIL2A_20200426T101549_N0214_R065_T32UNC_20200426T141031'
 b'S2B_MSIL2A_20200429T102559_N0214_R108_T32UNC_20200429T134751'
 b'S2A_MSIL2A_20200501T102031_N0214_R065_T32UNC_20200501T134143'
 b'S2A_MSIL2A_20200504T103031_N0214_R108_T32UNC_20200504T130404'
 b'S2B_MSIL2A_20200506T101559_N0214_R065_T32UNC_20200506T145433'
 b'S2B_MSIL2A_20200509T102559_N0214_R108_T32UNC_20200509T135055'
 b'S2A_MSIL2A_20200511T102031_N0214_R065_T32UNC_20200511T130304'
 b'S2A_MSIL2A_20200514T103031_N0214_R108_T32UNC_20200514T111457'
 b'S2B_MSIL2A_20200516T101559_N0214_R065_T32UNC_20200516T134122'
 b'S2B_MSIL2A_20200519T102559_N0214_R108_T32UNC_20200519T150634'
 b'S2A_MSIL2A_20200521T102031_N0214_R065_T32UNC_20200521T115134'
 b'S2A_MSIL2A_20200524T103031_N0214_R108_T32UNC_20200524T135735'
 b'S2B_MSIL2A_20200526T101559_N0214_R065_T32UNC_20200526T135521'
 b'S2B_MSIL2A_20200529T102559_N0214_R108_T32UNC_20200529T135455'
 b'S2A_MSIL2A_20200531T102031_N0214_R065_T32UNC_20200531T134031'
 b'S2A_MSIL2A_20200603T103031_N0214_R108_T32UNC_20200603T163921'
 b'S2B_MSIL2A_20200605T101559_N0214_R065_T32UNC_20200605T135751'
 b'S2B_MSIL2A_20200608T102559_N0214_R108_T32UNC_20200608T140703'
 b'S2A_MSIL2A_20200610T102031_N0214_R065_T32UNC_20200610T125245'
 b'S2A_MSIL2A_20200613T103031_N0214_R108_T32UNC_20200613T111252'
 b'S2B_MSIL2A_20200615T101559_N0214_R065_T32UNC_20200615T141117'
 b'S2B_MSIL2A_20200618T102559_N0214_R108_T32UNC_20200618T143719'
 b'S2A_MSIL2A_20200620T102031_N0214_R065_T32UNC_20200620T115213'
 b'S2A_MSIL2A_20200623T103031_N0214_R108_T32UNC_20200623T142851'
 b'S2B_MSIL2A_20200625T101559_N0214_R065_T32UNC_20200625T134347'
 b'S2B_MSIL2A_20200628T102559_N0214_R108_T32UNC_20200628T134715'
 b'S2A_MSIL2A_20200630T102031_N0214_R065_T32UNC_20200630T141810'
 b'S2A_MSIL2A_20200703T103031_N0214_R108_T32UNC_20200703T130401'
 b'S2B_MSIL2A_20200705T101559_N0214_R065_T32UNC_20200705T135630'
 b'S2B_MSIL2A_20200708T102559_N0214_R108_T32UNC_20200708T135942'
 b'S2A_MSIL2A_20200710T102031_N0214_R065_T32UNC_20200710T125814'
 b'S2A_MSIL2A_20200713T103031_N0214_R108_T32UNC_20200713T111204'
 b'S2B_MSIL2A_20200715T101559_N0214_R065_T32UNC_20200715T142122'
 b'S2B_MSIL2A_20200718T102559_N0214_R108_T32UNC_20200718T140654'
 b'S2A_MSIL2A_20200720T102031_N0214_R065_T32UNC_20200720T115114'
 b'S2A_MSIL2A_20200723T103031_N0214_R108_T32UNC_20200723T142801'
 b'S2B_MSIL2A_20200725T101559_N0214_R065_T32UNC_20200725T135708'
 b'S2B_MSIL2A_20200728T102559_N0214_R108_T32UNC_20200728T140633'
 b'S2A_MSIL2A_20200730T102031_N0214_R065_T32UNC_20200730T110107'
 b'S2A_MSIL2A_20200802T103031_N0214_R108_T32UNC_20200802T131621'
 b'S2B_MSIL2A_20200804T101559_N0214_R065_T32UNC_20200804T134431'
 b'S2B_MSIL2A_20200807T102559_N0214_R108_T32UNC_20200807T132026'
 b'S2A_MSIL2A_20200809T102031_N0214_R065_T32UNC_20200809T130506'
 b'S2A_MSIL2A_20200812T103031_N0214_R108_T32UNC_20200812T131334'
 b'S2B_MSIL2A_20200814T101559_N0214_R065_T32UNC_20200814T130939'
 b'S2B_MSIL2A_20200817T102559_N0214_R108_T32UNC_20200817T123809'
 b'S2A_MSIL2A_20200819T102031_N0214_R065_T32UNC_20200819T131359'
 b'S2A_MSIL2A_20200822T103031_N0214_R108_T32UNC_20200822T131718'
 b'S2B_MSIL2A_20200824T101559_N0214_R065_T32UNC_20200824T135410'
 b'S2B_MSIL2A_20200827T102559_N0214_R108_T32UNC_20200827T135039'
 b'S2A_MSIL2A_20200829T102031_N0214_R065_T32UNC_20200829T131252'
 b'S2A_MSIL2A_20200901T103031_N0214_R108_T32UNC_20200901T150718'
 b'S2B_MSIL2A_20200903T101559_N0214_R065_T32UNC_20200903T134943'
 b'S2B_MSIL2A_20200906T102559_N0214_R108_T32UNC_20200906T132601'
 b'S2A_MSIL2A_20200908T102031_N0214_R065_T32UNC_20200908T130954'
 b'S2A_MSIL2A_20200911T103031_N0214_R108_T32UNC_20200911T132157'
 b'S2B_MSIL2A_20200913T101629_N0214_R065_T32UNC_20200913T131152'
 b'S2B_MSIL2A_20200916T102649_N0214_R108_T32UNC_20200916T132658'
 b'S2A_MSIL2A_20200918T102031_N0214_R065_T32UNC_20200918T120844'
 b'S2A_MSIL2A_20200921T103031_N0214_R108_T32UNC_20200921T151006'
 b'S2B_MSIL2A_20200923T101649_N0214_R065_T32UNC_20200923T135729'
 b'S2B_MSIL2A_20200926T102709_N0214_R108_T32UNC_20200926T141718'
 b'S2A_MSIL2A_20200928T102031_N0214_R065_T32UNC_20200928T131819'
 b'S2A_MSIL2A_20201001T103031_N0214_R108_T32UNC_20201001T135108'
 b'S2B_MSIL2A_20201003T101759_N0214_R065_T32UNC_20201003T145325'
 b'S2B_MSIL2A_20201006T102819_N0214_R108_T32UNC_20201006T132503'
 b'S2A_MSIL2A_20201008T102031_N0214_R065_T32UNC_20201008T131321'
 b'S2A_MSIL2A_20201011T103031_N0214_R108_T32UNC_20201011T132248'
 b'S2B_MSIL2A_20201013T101909_N0214_R065_T32UNC_20201013T122253'
 b'S2B_MSIL2A_20201016T102929_N0214_R108_T32UNC_20201016T122900'
 b'S2A_MSIL2A_20201018T102041_N0214_R065_T32UNC_20201018T115707'
 b'S2A_MSIL2A_20201021T103101_N0214_R108_T32UNC_20201021T132152'
 b'S2B_MSIL2A_20201023T102029_N0214_R065_T32UNC_20201023T130606'
 b'S2B_MSIL2A_20201026T103039_N0214_R108_T32UNC_20201026T132439'
 b'S2A_MSIL2A_20201028T102141_N0214_R065_T32UNC_20201028T120642'
 b'S2A_MSIL2A_20201031T103201_N0214_R108_T32UNC_20201031T131751'
 b'S2B_MSIL2A_20201102T102159_N0214_R065_T32UNC_20201102T130730'
 b'S2B_MSIL2A_20201105T103229_N0214_R108_T32UNC_20201105T122330'
 b'S2A_MSIL2A_20201107T102231_N0214_R065_T32UNC_20201107T131525'
 b'S2A_MSIL2A_20201110T103251_N0214_R108_T32UNC_20201110T131947'
 b'S2B_MSIL2A_20201112T102259_N0214_R065_T32UNC_20201112T123810'
 b'S2B_MSIL2A_20201115T103309_N0214_R108_T32UNC_20201115T123511'
 b'S2A_MSIL2A_20201117T102321_N0214_R065_T32UNC_20201117T114439'
 b'S2A_MSIL2A_20201120T103341_N0214_R108_T32UNC_20201120T131928'
 b'S2B_MSIL2A_20201122T102339_N0214_R065_T32UNC_20201122T122607'
 b'S2B_MSIL2A_20201125T103349_N0214_R108_T32UNC_20201125T123629'
 b'S2A_MSIL2A_20201127T102401_N0214_R065_T32UNC_20201127T115554'
 b'S2A_MSIL2A_20201130T103411_N0214_R108_T32UNC_20201130T131708'
 b'S2B_MSIL2A_20201202T102409_N0214_R065_T32UNC_20201202T123050'
 b'S2B_MSIL2A_20201205T103419_N0214_R108_T32UNC_20201205T123240'
 b'S2A_MSIL2A_20201207T102411_N0214_R065_T32UNC_20201207T131913'
 b'S2A_MSIL2A_20201210T103431_N0214_R108_T32UNC_20201210T131636'
 b'S2B_MSIL2A_20201212T102329_N0214_R065_T32UNC_20201212T123109'
 b'S2B_MSIL2A_20201215T103339_N0214_R108_T32UNC_20201215T122336'
 b'S2A_MSIL2A_20201217T102431_N0214_R065_T32UNC_20201217T114450'
 b'S2A_MSIL2A_20201220T103441_N0214_R108_T32UNC_20201220T132219'
 b'S2B_MSIL2A_20201222T102339_N0214_R065_T32UNC_20201222T123326'
 b'S2B_MSIL2A_20201225T103339_N0214_R108_T32UNC_20201225T121034'
 b'S2A_MSIL2A_20201227T102431_N0214_R065_T32UNC_20201227T120624'
 b'S2A_MSIL2A_20201230T103441_N0214_R108_T32UNC_20201230T131555']

In [13]:
len(size_s1_asc), len(size_s1_des), len(size_s2)

(50374, 50374, 50374)

In [3]:
max(size_s1_asc), max(size_s1_des), max(size_s2)

(149, 257, 146)

In [14]:
size_s2 = np.array(size_s2)
petits = size_s2[size_s2 < 10]

In [15]:
len(petits)

6053

In [8]:
import numpy as np
np.argmin(size_s2)

1991

In [15]:
min(size_s1_asc), min(size_s1_des), min(size_s2)

(23, 27, 6)

In [19]:
import numpy as np
sum(np.array(size_s2) > 70)

20729

In [26]:
from timm.layers import PatchEmbed, trunc_normal_, PatchDropout
from timm.models._manipulate import named_apply, checkpoint_seq

/home/GAstruc/anaconda3/envs/myenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

:

In [194]:
from torch.utils.data import Dataset
from hydra.utils import instantiate
import h5py
import numpy as np
import json
from src.data.utils import subset_dict_by_filename, filter_labels_by_threshold
from skmultilearn.model_selection import iterative_train_test_split
import torch
import rasterio
import random

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

class TreeSAT(Dataset):
    def __init__(
        self,
        path,
        transform,
        split: str = "train",
        classes: list = [],
        partition: float = 1.,
        aerial: bool = True,
        s2: bool = True,
        s1_asc: bool = True,
        s1_des: bool = True,
        ):
        """Initializes the dataset.
        Args:
            path (str): path to the dataset
            transform (torchvision.transforms): transform to apply to the data
            split (str): split to use (train, val, test)
            classes (list): name of the differrent classes to use
            partition (float): proportion of the dataset to keep
            aerial: bool = True,
            s2: bool = True,
            s1_asc: bool = True,
            s1_des: bool = True,
        """
        self.path = path
        self.transform = instantiate(transform)
        self.partition = partition
        self.aerial = aerial
        self.s2 = s2
        self.s1_asc = s1_asc
        self.s1_des = s1_des
        self.sentinel = s2 or s1_asc or s1_des
        data_path = path + split + "_filenames.lst"
        with open(data_path, 'r') as file:
            self.data_list = [line.strip() for line in file.readlines()]
        self.load_labels(classes)
            
    def load_labels(self, classes):
        with open(self.path + "labels/TreeSatBA_v9_60m_multi_labels.json") as file:
            jfile = json.load(file)
            subsetted_dict = subset_dict_by_filename(self.data_list, jfile)
            labels = filter_labels_by_threshold(subsetted_dict, 0.07)
            lines = list(labels.keys())

        y = [[0 for i in range(len(classes))] for line in lines]
        for i, line in enumerate(lines):
            for u in labels[line]:
                y[i][classes.index(u)] = 1

        self.data_list, self.labels, _, _ = iterative_train_test_split(np.expand_dims(np.array(lines), axis=1), np.array(y), test_size = 1. - self.partition)
        self.data_list = list(np.concatenate(self.data_list).flat)

    def __getitem__(self, i):
        """Returns an item from the dataset.
        Args:
            i (int): index of the item
        Returns:
            dict: dictionary with keys "img", "gps", "idx" and optionally "label"
        """
        name = self.data_list[i]
        output = {'label': self.labels[name]}
    
        if self.aerial:
            with rasterio.open(self.path + "aerial/" + name) as f:
                output["aerial"] = f.read()

        if self.sentinel:
            with h5py.File(self.path + "patches-dataset/" + name, 'r') as file:
                if self.s1_asc:
                    output["s1_asc"] = file["sen-1-asc-data"][:]
                if self.s1_des:
                    output["s1_des"] = file["sen-1-des-data"][:]
                if self.s2:
                    output["s2"]= file["sen-2-data"][:]

        return self.transform(output)

    def __len__(self):
        return len(self.data_list)

In [195]:
dataset = TreeSAT(path='/home/GAstruc/PhD/treesat_benchmark/data/',
        transform=None,
        split = "train",
        classes = ["Abies",
            "Acer",
            "Alnus",
            "Betula",
            "Cleared",
            "Fagus",
            "Fraxinus",
            "Larix",
            "Picea",
            "Pinus",
            "Populus",
            "Prunus",
            "Pseudotsuga",
            "Quercus",
            "Tilia"],
        partition = 1.,
        aerial = True,
        s2 = True,
        s1_asc = True,
        s1_des = True,)

In [1]:
name = dataset.data_list[i]
output = {'label': dataset.labels[i]}

if dataset.aerial:
    with rasterio.open(dataset.path + "aerial/60m/" + name) as f:
        output["aerial"] = f.read()

if dataset.sentinel:
    with h5py.File(dataset.path + "sentinel/" + name.split('.')[0] + ".h5", 'r') as file:
        if dataset.s1_asc:
            output["s1_asc"] = file["sen-1-asc-data"][:]
        if dataset.s1_des:
            output["s1_des"] = file["sen-1-des-data"][:]
        if dataset.s2:
            output["s2"]= file["sen-2-data"][:]

NameError: name 'dataset' is not defined

In [210]:
output['aerial'].shape

(4, 304, 304)

In [208]:
from torchvision import transforms
import torch

class TreeSATTransform(transforms.Transform):
    def __init__(self):
        super().__init__()

    def __call__(self, batch):
        keys = list(batch.keys())
        for key in keys:
            batch[key] = torch.tensor()
        return img.convert("L")

transform = TreeSATTransform()

AttributeError: module 'torchvision.transforms' has no attribute 'Transform'

In [182]:
dataset.__getitem__(0)

IndexError: too many indices for tensor of dimension 3

In [169]:
import os
import shutil

In [171]:
#files = os.listdir('/var/data/gastruc/data/sentinel/patches-dataset')
files = os.listdir('/home/GAstruc/patches-dataset')

In [174]:
files[0], '_'.join(files[0].split('_')[:-1]) + ".h5"

('Fraxinus_excelsior_5_34359_WEFL_NLF_2016.h5',
 'Fraxinus_excelsior_5_34359_WEFL_NLF.h5')

In [178]:
import shutil

for file in files:
    shutil.copy('/home/GAstruc/patches-dataset/' + file, '/home/GAstruc/PhD/treesat_benchmark/data/sentinel/' + '_'.join(file.split('_')[:-1]) + ".h5")

In [1]:
import h5py
import torch
from datetime import datetime

In [2]:
def day_number_in_year(date_arr, place=4):
    day_number = []
    for date_string in date_arr:
        date_object = datetime.strptime(str(date_string).split('_')[place][:8], '%Y%m%d')
        day_number.append(date_object.timetuple().tm_yday) # Get the day of the year
    return torch.tensor(day_number)

In [12]:
output = {}
with h5py.File("/home/GAstruc/PhD/PhD/data/TreeSat/sentinel/Abies_alba_0_2545_WEFL_NLF.h5", 'r') as file:
    output["s2-mae"]= torch.tensor(file["sen-2-data"][:])[:, :10, :]
    dates = day_number_in_year(file["sen-2-products"][:], place=2)
    print(dates)
    l = []
    for i in range(1, 5):
        mask = ((dates >= 91 * i) & (dates < 91 * (i+1)))
        if sum(mask) > 0:
            print(output["s2-mae"][mask].shape)
            r, _ = torch.median(output["s2-mae"][mask], dim = 0)
            print(r.shape)
            l.append(r)
        else:
            l.append(torch.zeros((output["s2-mae"].shape[1], output["s2-mae"].shape[-2], output["s2-mae"].shape[-1])))
    output["s2-mae"] = torch.cat(l)

tensor([306, 313, 316, 323, 326, 333, 336, 343, 346, 353, 356, 363, 366])
torch.Size([12, 10, 6, 6])
torch.Size([10, 6, 6])
torch.Size([1, 10, 6, 6])
torch.Size([10, 6, 6])

In [9]:
output["s2-mae"]

tensor([[[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        [[   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.],
         [   0.,    0.,    0.,    0.,    0.,    0.]],

        ...,

        [[1196., 1196., 1485., 1724., 1724., 1558.],
         [1196., 1196., 1485., 1724., 1724., 1558.],
         [1411., 1411., 1279., 1353., 1353.,  739.],
         [1131., 1131., 1078.,  927.,  927.,  658.],
         [1131., 1131., 1078.,  927.,  927.,  658.],
         [ 894.,  894.,  956.,  573.,  573.,  348.]],

        [[ 286.,  286.,  325.,  306.,  306.,  335.],
         [ 286.,  286.,  325.,  306.,  306.,  335.],
         [ 244.,  244.,  272.,  235.,  235.,  209.],
         [ 218.,  218.,  225.,  193.,  193.,  120.],
         [ 218.,  218.,  225.,  193.,  193.,  120.],
         [ 199.,  199.,  173.,   88.,   88.,   77.]],

        [[ 113.,  113.,  152.,  118.,  118.,  103.],
         [ 113.,  113.,  152.,  118.,  118.,  103.],
         [  99.,   99.,  128.,  110.,  110.,   63.],
         [  80.,   80.,   94.,  111.,  111.,   51.],
         [  80.,   80.,   94.,  111.,  111.,   51.],
         [  66.,   66.,   86.,   63.,   63.,   32.]]])

In [8]:
output["s2-mae"].shape

torch.Size([40, 6, 6])

In [3]:
from datasets import load_dataset
dataset = load_dataset('osv5m/osv5m', full=True)

/home/GAstruc/anaconda3/envs/myenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DatasetNotFoundError: Dataset 'osv5m/osv5m' doesn't exist on the Hub or cannot be accessed. If the dataset is private or gated, make sure to log in with `huggingface-cli login` or visit the dataset page at https://huggingface.co/datasets/osv5m/osv5m to ask for access.

In [4]:
!huggingface-cli login --token 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

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/GAstruc/.cache/huggingface/token
Login successful

In [4]:
from huggingface_hub import snapshot_download
snapshot_download(repo_id="osv5m/osv5m", local_dir="datasets/OpenWorld", repo_type='dataset', cache_dir="datasets/OpenWorld")

Fetching 108 files:   2%|▏         | 2/108 [00:00<00:17,  6.11it/s]Error while downloading from https://cdn-lfs-us-1.huggingface.co/repos/f5/73/f573bcb65d595bafc2fee069d189e06507652c64f93b4c4860f021f37dfccbe3/d5e323b36ff953705942681ff0edeb47820158ab2d58e34218332624a4def254?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%2700.zip%3B+filename%3D%2200.zip%22%3B&response-content-type=application%2Fzip&Expires=1713785448&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzc4NTQ0OH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zL2Y1LzczL2Y1NzNiY2I2NWQ1OTViYWZjMmZlZTA2OWQxODllMDY1MDc2NTJjNjRmOTNiNGM0ODYwZjAyMWYzN2RmY2NiZTMvZDVlMzIzYjM2ZmY5NTM3MDU5NDI2ODFmZjBlZGViNDc4MjAxNThhYjJkNThlMzQyMTgzMzI2MjRhNGRlZjI1ND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=kgltL-a9Te1ar5SSkfsqb-DO41w4JhkiYYRJJJBlBug4--8vQUjFdimdUe1-E4WX1BznawZzHp5CAV4Dlhb-a1ZfHJrL1JYo%7E%7EmcnPdpmfSoygMav7QjZRiYC1yaAG3KuWwryAkjiWa4hY%7EVzZUAsxq-t9yOBcEcQjsSggx1nIPXs3TuzdQDXFSRwvk7dp15gd6n%7Ek61RPa1OiVZFF8lgJvPQRx%7El1W%7EeQSYHc5aBzKGejr5pYZjowrngnv91xKpckxzdA7%7EoI8ZgekrjYwvr9FP1RPNWIlC-bd3DB1yQANHTY4iquYwxb7SfRt7gbdSoyKwAHN%7EyaVCjCDZ4y-mGw__&Key-Pair-Id=KCD77M1F0VK2B: HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out.
Trying to resume download...
Error while downloading from https://cdn-lfs-us-1.huggingface.co/repos/f5/73/f573bcb65d595bafc2fee069d189e06507652c64f93b4c4860f021f37dfccbe3/54d4d3ba176a6cbc8fe822df37060bf5a82387806e1ae7c2ce3e7ec999ab3dbc?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%2703.zip%3B+filename%3D%2203.zip%22%3B&response-content-type=application%2Fzip&Expires=1713785448&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzc4NTQ0OH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zL2Y1LzczL2Y1NzNiY2I2NWQ1OTViYWZjMmZlZTA2OWQxODllMDY1MDc2NTJjNjRmOTNiNGM0ODYwZjAyMWYzN2RmY2NiZTMvNTRkNGQzYmExNzZhNmNiYzhmZTgyMmRmMzcwNjBiZjVhODIzODc4MDZlMWFlN2MyY2UzZTdlYzk5OWFiM2RiYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=c2Zl09lceI598myE4ZG883jKdSHD7bIA-mJLqaoF94vpf-o-Gt2Oe6PujSauddoUxkhXm2XndZv4kWs8phQVL6c5y0AMyEjyr8xf-sAQYeQ5xTbDoUZhZMOfZTVlUbl0xSXCX13hawVWgqe51U41MkX5CsSOaDkEkL678VSHcRIgh7OuzOcEXtgYGfzwiU9P8VeHrbzD4bhxdxBc6jEodqSEgdkRQOtmwdUdgpIiUmhGkoREcdXhPaM9E%7E0GcZoa422qjcwa1BbUzx3BirSYlaPzYga8T8rt9EGXQF0c3LIbmjVUpZIoljvvgKbpVUlz4YLrxJ7g7tPST1E6NWUIfg__&Key-Pair-Id=KCD77M1F0VK2B: HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out.
Trying to resume download...
Error while downloading from https://cdn-lfs-us-1.huggingface.co/repos/f5/73/f573bcb65d595bafc2fee069d189e06507652c64f93b4c4860f021f37dfccbe3/1a7e529117a9f8f9f80c033243b08d1c56818e243d094750c27024eaec17b3d0?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%2704.zip%3B+filename%3D%2204.zip%22%3B&response-content-type=application%2Fzip&Expires=1713785852&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMzc4NTg1Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zL2Y1LzczL2Y1NzNiY2I2NWQ1OTViYWZjMmZlZTA2OWQxODllMDY1MDc2NTJjNjRmOTNiNGM0ODYwZjAyMWYzN2RmY2NiZTMvMWE3ZTUyOTExN2E5ZjhmOWY4MGMwMzMyNDNiMDhkMWM1NjgxOGUyNDNkMDk0NzUwYzI3MDI0ZWFlYzE3YjNkMD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=WeasxoLf%7EXNzkE%7ED79Bc7BQRnniU8o-Squpj1tfM15JGw9c-Stple7Qq%7EQPk0ALQajLA3JNVwWrD-YVI35X%7E4UfxmwUsL6ib9v9ty11T9P4r2BguwZm%7Eq5%7E2YGEI2-1SRYgNvakz8UwJFcZMhH4grZNUhYN5mrooUs37eydhSYO2LhHoozfI9dFadxkiqogScsJEmsSBW4BayyhMvWyE633z%7Eew0%7EFYu8%7Eee3kQ4AarVWnmKflQQe4htaFbpF7yU17INY6cyynKBklmIhAxQ1Jygbfry-OV-jBgeFawFyHjT6SfCy8pSjdhmp%7EvqnMk2H1iVGyQlmGv7WH47lcdsgA__&Key-Pair-Id=KCD77M1F0VK2B: HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out.
Trying to resume download...
Fetching 108 files:   2%|▏         | 2/108 [15:29<13:41:24, 464.95s/it]

In [3]:
import os
for root, dirs, files in os.walk("osv5m"):
    print(root, dirs, files)

osv5m ['images'] ['.gitattributes', 'README.md']
osv5m/images ['test'] []
osv5m/images/test [] ['04.zip', '00.zip', '03.zip']

In [ ]:
import os
import zipfile
for root, dirs, files in os.walk("osv5m"):
    for file in files:
        if file.endswith(".zip"):
            with zipfile.ZipFile(os.path.join(root, file), 'r') as zip_ref:
                zip_ref.extractall(root)
                os.remove(os.path.join(root, file))

In [5]:
from PIL import Image
from models.huggingface import Geolocalizer

gelocalizer = Geolocalizer.from_pretrained('osv5m/baseline')
img = Image.open('.media/examples/img1.jpeg')
x = gelocalizer.transform(img).unsqueeze(0) # transform the image using our dedicated transformer
gps = geolocalizer(x) # B, 2 (lat, lon - tensor in rad)

In [5]:
from PIL import Image
from models.huggingface import Geolocalizer

geolocalizer = Geolocalizer.from_pretrained('osv5m/baseline')

In [6]:
img = Image.open('.media/examples/img1.jpeg')
x = geolocalizer.transform(img).unsqueeze(0) # transform the image using our dedicated transformer

In [7]:
gps = geolocalizer(x) # B, 2 (lat, lon - tensor in rad)

In [8]:
gps

tensor([[0.5692, 2.3100]], dtype=torch.float64, grad_fn=<MulBackward0>)

In [13]:
from huggingface_hub import hf_hub_url, hf_hub_download
repo_url = "osv5m/baseline"  # Replace with your desired URL
filename = "pytorch_model.bin"
download_url = hf_hub_url(repo_url, filename=filename)
hf_hub_download(download_url, filename=filename)

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'https://huggingface.co/osv5m/baseline/resolve/main/pytorch_model.bin'. Use `repo_type` argument if needed.